### ISSUE TITLE
NSP Prototype Pollution Attack issue

### ISSUE THREAD

**Issue by alexlapinski** [Surnet/swagger-jsdoc#100]
It looks like a new NSP security issue has been found in one of the deep dependencies that swagger-jsdoc has. (https://nodesecurity.io/advisories/566) 

![nsp-issue](https://user-images.githubusercontent.com/37541/36331471-ecc1e8a8-133b-11e8-8600-0fcb7a73708d.png)

**Comment by ehmicky** [comment]
There is also [this vulnerability](https://snyk.io/vuln/npm:braces:20180219) on `braces`.

```
Introduced through: api-service@Cardero-X/api-service#815b1c3e71cc7020a8c963c7e01db7be2cee01d0 › swagger-jsdoc@https://github.com/ehmicky/swagger-jsdoc › chokidar@1.7.0 › anymatch@1.3.2 › micromatch@2.3.11 › braces@1.8.5
```

**Comment by RaedJarrar** [comment]
Is there any follow up on this? Right now, we are forced to add this to a list of exceptions. It would be nice to get a fix for this.

**Comment by kibertoad** [comment]
@chdanielmueller @kalinchernev Any chance this could be addressed or write permissions assigned to additional people to review and merge?..

**Comment by kalinchernev** [comment]
#110 has been merged and a new release has been published on npm for this.
No vulnerabilities are being reported by snyk at the moment, so I'm closing the issue.
