### ISSUE TITLE
Parsing error on comment

### ISSUE THREAD

**Issue by Nyhillius** [Surnet/swagger-jsdoc#102]
Hello,

I think I have isolated a parsing error on the comment documentation declaration.
On my response API example, I have an object called "response" and Swagger is telling me that it is deprecated but it is on example declaration, see below.
![screenshot_1](https://user-images.githubusercontent.com/17960462/37031700-d72637ec-2150-11e8-89f2-1363f4e9b93f.png)
![screenshot_2](https://user-images.githubusercontent.com/17960462/37031701-d7445484-2150-11e8-8ce4-2e2bb79a60e4.png)

**Comment by kalinchernev** [comment]
I've removed the deprecation messages since some time ago. Not only they have been left for too long and developers should have taken them into account, but they also caused more confusion than good.
The parser is checking these and for the rest singular to plural the fix is still in the package.
