### ISSUE TITLE
CORS cookie support

### ISSUE THREAD

**Issue by JeremyColton** [Surnet/swagger-jsdoc#116]
Hi, I have 2 servers: UI and API. To accommodate CORS:
a) The client login request sets:
`credentials: 'include'`
b) The login response has a "Set-Cookie" HTTP header. This works when run via my UI in Chrome.

I read that "Cookie authentication is supported in OpenAPI 3.0 but not in OpenAPI/Swagger 2.0" from https://stackoverflow.com/questions/36924317/how-to-use-cookies-in-swagger-editor but this comment didnt' receive any points so i'm not sure if it's correct.

https://swagger.io/docs/specification/2-0/authentication/ also doesn't have a cookie example but doesn't say that are not supported!

Set-cookie is supported by this project? This is a limitation of OpenAPI 2.0?
How do I describe both a) and b) above (so I can test it using web pages generated by swagger-ui-express) ?

**Comment by kalinchernev** [comment]
Hi @JeremyColton I haven't used this type of security model in version 2 of the specification to be honest.
Have you seen this article and example about [cookie authentication](https://swagger.io/docs/specification/authentication/cookie-authentication/)? It's based on version 3 of the spec, so it's possible that version 2 does not support it, but if you share your example I'll be able to dig a bit further in the details.
