### ISSUE TITLE
NPM version 1.10.3 is not tagged on GitHub.

### ISSUE THREAD

**Issue by wibobm** [Surnet/swagger-jsdoc#123]
Same as subject ;)

**Comment by kalinchernev** [comment]
The only reason I sometimes publish releases on Github is that maybe some day there will be a conventional or standard change log generation which will rely on these tags. Otherwise, npm is the means user take the package I believe.

**Comment by wibobm** [comment]
The tags allow people to review the changes between versions when no release notes are provided.  That should be the only justification required for this wonderful project.

**Comment by kalinchernev** [comment]
@wibobm it's done :)
