### ISSUE TITLE
Using Swagger-jsdoc with or without cli not working, Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by travis5491811** [Surnet/swagger-jsdoc#132]
I'm trying to learn how to use swagger and swagger-jsdoc in my API's by example. 

I ended up having the same issue as the user [here](https://github.com/Surnet/swagger-jsdoc/issues/71) and found that thread. The links to clarify the example with and without CLI are no longer working (404). 

The way I intend to use `swagger-jsdoc` is by writing swagger definitions along side my mocha/chia implementation test. So when i need to update or add a route, i add a test case for it, and add swagger-jsdocs above the test for that route. Then I'd like to use the cli to generate updated swagger docs.

I'm trying to use the [getting started example](https://github.com/Surnet/swagger-jsdoc/blob/master/docs/GETTING-STARTED.md).

When i take the following and put it in say "example.test.js"
```
/**
 * @swagger
 *
 * /login:
 *   post:
 *     description: Login to the application
 *     produces:
 *       - application/json
 *     parameters:
 *       - name: username
 *         description: Username to use for login.
 *         in: formData
 *         required: true
 *         type: string
 *       - name: password
 *         description: User's password.
 *         in: formData
 *         required: true
 *         type: string
 *     responses:
 *       200:
 *         description: login
 */
```

And the following in a "api.js" file in the same directory as the file above:
```
const swaggerJSDoc = require('swagger-jsdoc');

const options = {
  info: {
    title: 'Hello World', // Title (required)
    version: '1.0.0', // Version (required)
  },
  // Path to the API docs
  apis: ['./example.test.js'],
};

// Initialize swagger-jsdoc -> returns validated swagger spec in json format
const swaggerSpec = swaggerJSDoc(options);
```
And then run `node_modules/swagger-jsdoc/bin/swagger-jsdoc.js -d api.js -o doc.json`

I get the following now:
```
Unexpected token u in JSON at position 0
Error while loading definition file 'api.js':
SyntaxError: Unexpected token u in JSON at position 0
```
I also looked [here](https://github.com/Surnet/swagger-jsdoc/blob/master/test/example/v3/petstore/api.js) for clues and did not find a solution. Just adding the jsdoc comments and running `npm test` gives the same JSON error when i try to console.log the output of `swaggerSpec`.

What am i doing wrong?

**Comment by travis5491811** [comment]
This [guide](https://www.oodlestechnologies.com/blogs/Integrate-Swagger-in-your-NodeJS-Application) provided a good example to get me moving further. Would be helpful to know if the method they are using is what you recommend and if so, add this to the documentation. I can add it as a full step by step example in the example folder as a `.md` if you agree that it might be helpful to others as well.

**Comment by kalinchernev** [comment]
Hi @travis5491811 thanks for the detailed feedback!
On first look, it seems that you are adding `apis` in your definition. This usage is targeted for the Node API (`const swaggerSpec = swaggerJSDoc(options);`)
If you want to use the CLI, you need to set these paths as parameters like this https://github.com/Surnet/swagger-jsdoc/blob/master/test/cli/cli.js#L94
where `example/v2/routes.js` is what you'd pass to `apis` when using Node API.
Opening the example definition file https://github.com/Surnet/swagger-jsdoc/blob/master/example/v2/swaggerDef.js it doesn't have this `apis` key because it will come from the CLI.
The example guide you've found looks fine when using the Node API.

**Comment by travis5491811** [comment]
Thanks @kalinchernev

**Comment by kalinchernev** [comment]
Hi @travis5491811 and thanks for closing the issue, I hope you've managed to find a solution.
I took inspiration from your detailed question and updated the documentation with a [new section about the ways you can work out the definition and the input arguments](https://github.com/Surnet/swagger-jsdoc#fundamental-concepts) depending on the way you want to use the program. I hope it makes it a bit more accessible.

**Comment by travis5491811** [comment]
@kalinchernev Thank you for trying to make this more accessible! It makes a huge impact in the number of people/projects that are able to get on board documenting their API's using OpenAPI specifications. I'm pretty excited about moving all my api documentation to OpenAPI spec and improving the documentation and consumption experience with my APIs. I'm still learning a lot about the OpenAPI spec and hope opensource adoption and tooling for it continues to grow. As I learn more about it and implement it into my projects I'll be able to contribute more. 

My current recipe for my Node/Express API is as follows:

```JavaScript
// app.js

// Swagger and swagger-jsdoc
const swaggerJSDoc = require('swagger-jsdoc');
// Swagger UI for express used to serve swagger-ui with output of swagger-jsdoc
const swaggerUi = require('swagger-ui-express');


// swagger definition
const swaggerDefinition = {
  info: {
    title: 'Example Swagger API',
    version: '2.0.0',
    description: 'This is the Example API documentation and is using the OpenAPI spec.',
  },
  host: `localhost:3000`,
  basePath: '/',
};

// options for swagger jsdoc 
const swaggerOptions = {
  swaggerDefinition: swaggerDefinition, // swagger definition
  apis: [
    './test/testfile1.js', //a file with mocha test and swagger specs written above each implementation test
    './tset/testfile2.js', //a file with mocha test and swagger specs written above each implementation test
  ], // path where API specification are written
};

// initialize swaggerJSDoc generator (outputs swagger docs as JSON to variable)
const swaggerSpec = swaggerJSDoc(swaggerOptions);
// Server swagger at <apiurl>/docs using swagger-ui-express
app.use('/docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));

```

```JavaScript
// Example testfile1.js

/**
 * @swagger
 * /user:
 *   post:
 *     tags:
 *       - User
 *     description: Save user
 *     produces:
 *       - application/json
 *     parameters:
 *       - name: user
 *         description: User object
 *         in: body
 *         required: true
 *         schema:
 *           $ref: '#/definitions/User'
 *     responses:
 *       200:
 *         description: Return saved user
 */

// ...mocha implementation test for "Save User" goes here

```

The rest of my API works as it did before, but now users can go to `localhost:3000/docs` to see API docs with Swagger style and OpenAPI compliant (compliant _ish_ ...still in progress). Since i write implementation test for all API endpoints, I can now (with the help of `swagger-jsdoc` and `swagger-ui-express` in the recipe above) write my OpenAPI definitions for the endpoint I'm testing right above the test. The reason I'm not using `swagger-test` is it doesn't appear to be maintained anymore or have the coverage to allow me to eliminate mocha test. I am looking into building an alternative opensource version of [acquit](https://github.com/vkarpov15/acquit) that could generate documentation through mocha test through existing mocha keywords and possibly keywords added through prototypes. By then I should also be able to explore making a general (unlike [this for Koa](https://github.com/Darmikon/swagger-ui-koa)) version of `swagger-ui-express` that can be used with other languages as proposed by [this](https://github.com/scottie1984/swagger-ui-express/pull/54) user.

**Comment by kalinchernev** [comment]
@travis5491811 nice! Haven't thought of adding specification chunks in test files to be honest. Before, CLI used to have watch mode with chokidar, if it wasn't removed then you could have spawned watch in test and CLI so to update both at the same time.
To me, keeping the documentation closer to the actual code makes more sense as when you update the code which serves the API endpoint, it will be more natural to find the documentation right above and update it as well. Keeping the documentation code in the test suite means you'll need to have rich coverage of cases and/or snapshot testing of responses, so that each single small change of the API implementation changes to trigger failures in the tests.

Thanks for sharing! :))
