### ISSUE TITLE
Specify OpenAPI 3.x vs Swagger 2.0

### ISSUE THREAD

**Issue by Dalabad** [Surnet/swagger-jsdoc#134]
Is there any way to specify whether I want 

- OpenAPI 3.x
- or Swagger 2.0

either in the annotations or during the CLI execution?

Currently it is always generating a valid swagger 2.0 file. How can i specify that I want a OpenAPI 3.x file?

Thanks in advance

**Comment by kalinchernev** [comment]
Hi @Dalabad yes, you can. You can add a flag for open api specification [like this](https://github.com/Surnet/swagger-jsdoc/blob/master/test/example/v3/test.js#L34) in your definition.

**Comment by Dalabad** [comment]
Hi @kalinchernev Thanks a lot for the fast response.
Thats exactly what I was looking for. I was just expecting it, to be somewhere within the examples, didn't think about the tests folder.
