### ISSUE TITLE
Schema reference in other schema not shown in 'try' editor (v3)

### ISSUE THREAD

**Issue by lacivert** [Surnet/swagger-jsdoc#136]
If I write a ref to other schema component inside it, I don't see it in editor:

```
 * components:
 *   schemas:
 *     ScrollingMessageType:
 *       properties:
 *         id:
 *           type: number
 *         name:
 *           type: string
 *       examples:
 *         static:
 *           summary: A static scrolling message type
 *           value: {"id":0, "name": "static"}
 *         dynamic:
 *           summary: A dynamic scrolling message type
 *           value: {"id":1, "name": "dynamic"}
 *     ScrollingMessage:
 *       properties:
 *         team:
 *           type: string
 *         msgtype:
 *           schema:
 *             $ref: '#/components/schemas/ScrollingMessageType'
```

<img width="437" alt="screen shot 2018-10-05 at 15 29 29" src="https://user-images.githubusercontent.com/945612/46535267-815f2e80-c8b3-11e8-9860-113747477d14.png">

But if I write it as object (not ref), I see it;

```
* components:
 *   schemas:
 *     ScrollingMessage:
 *       properties:
 *         team:
 *           type: string
 *         msgtype:
 *           examples:
 *             static:
 *               summary: A static scrolling message type
 *               value: {"id":0, "name": "static"}
 *             dynamic:
 *               summary: A dynamic scrolling message type
 *               value: {"id":1, "name": "dynamic"}
 *           type: object
 *           properties:
 *             id:
 *               type: number
 *             name:
 *               type: string
```

<img width="309" alt="screen shot 2018-10-05 at 15 33 31" src="https://user-images.githubusercontent.com/945612/46535439-0f3b1980-c8b4-11e8-9150-e25402b98ab0.png">

By the way, examples not shown in both.

**Comment by kalinchernev** [comment]
Hi @lacivert,

You'll need to report this issue in the queue of [swagger editor tool](https://github.com/swagger-api/swagger-editor). Having a brisk look at the first page with issues I noticed [another one related to the examples](https://github.com/swagger-api/swagger-editor/issues/1893) which makes me believe their rendering needs tweaks.

The way I can ensure it's not an issue with swagger-jsdoc is by using the official examples from the OpenAPI github repository which are also base of our parsing examples.

The examples related to APIs with examples are [here](https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/yaml/api-with-examples.yaml) and [here](https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/api-with-examples.yaml) for versions 2 and 3.

Even using these official examples which are 100% valid specifications, the editor is not showing the examples section in version 3. This confirms your discovery of the issue which you can submit to the team of swagger-editor.

I hope I managed to explain my road of finding which tool is the one responsible for your issue. By the way, I also tried [swagger UI](https://swagger.io/tools/swagger-ui/) which also does not displays examples for version 3 of the specification. You might need to check which is the common denominator between swagger editor and ui which displays the parsed specification.

**Comment by lacivert** [comment]
Thank you for your kind and detailed explanation. And sorry for the misunderstanding. I believe it was the result of my rush. I guess I already knew wagger-jsdoc project is not responsible of UI, but I made the mistake to open an issue of another project here.

Thank you for the research as well, I am goint to check the links.
