### ISSUE TITLE
Documentation, includding "Getting started", is wrong

### ISSUE THREAD

**Issue by marcospgp** [Surnet/swagger-jsdoc#137]
The examples describe the request body as a parameter with the attribute `in: body`, though this is not supported by the Open API 3.0 specification:

```
Parameter Locations
There are four possible parameter locations specified by the in field:

path - Used together with Path Templating, where the parameter value is actually part of the operation's URL. This does not include the host or base path of the API. For example, in /items/{itemId}, the path parameter is itemId.
query - Parameters that are appended to the URL. For example, in /items?id=###, the query parameter is id.
header - Custom headers that are expected as part of the request. Note that RFC7230 states header names are case insensitive.
cookie - Used to pass a specific cookie value to the API.
```

https://swagger.io/specification/#parameterObject

Edit: More info here https://swagger.io/docs/specification/describing-request-body/. It seems this was supported in OpenAPI 2.0, but this package explicitly supports OpenAPI 3.0.

Thank you guys!

**Comment by kalinchernev** [comment]
Yes, the example is for the default version 2.
