### ISSUE TITLE
Remove default "swagger: 2.0" 

### ISSUE THREAD

**Issue by marcospgp** [Surnet/swagger-jsdoc#138]
If you follow the readme and don't specify a swagger/openapi version in the definition, this library adds `"swagger": "2.0"`, right after the `info` block by default.

The problem is that I was using [redoc](https://github.com/Rebilly/ReDoc) and I didn't realize it was interpreting my spec as the older version.

I updated my definition object to this:

```js
const options = {
  definition: {
    info: {
      title: 'An API',
      version: '0.0.1',
    },
    openapi: '3.0.0'
  },
  // Path to the API docs
  apis: ['./routers/**/*.js'],
};
```

And Redoc now correctly interprets it as openapi 3.0.

I thought it would be a good idea to make the versioning more explicit, maybe by adding the `"swagger": "2.0"` explicitly in the readme examples. And perhaps by requiring the parameter instead of having a default?

Thanks!

**Comment by kalinchernev** [comment]
Hi @marcospgp the swagger-jsdoc package has increased its base of users in the [last couple of months](https://npm-stat.com/charts.html?package=swagger-jsdoc&from=2016-01-01&to=2018-10-09) to an extend where I will not make a change like this risking the break of dozens of thousands of users with comparison to those who adopt it because the package supports v2 AND v3, where v2 was supported years before.

**Comment by marcospgp** [comment]
I agree, breaking changes would not be a good idea. How about just editing the readme and explicitly adding `"swagger": "2.0"` or perhaps even `openapi: '3.0.0'` (which might be what most people are using now)?

As someone who was getting into Swagger for the first time, I thought Swagger 2.0 was the same as OpenAPI 3.0 😄 so maybe making that explicit would help other people!

**Comment by masonheverett** [comment]
I would also suggest making it clear either in the documentation or in an example that in order to use open api 3 you need to add it to the definition. It was unclear at least to me.

**Comment by kalinchernev** [comment]
Closing, @marcospgp kindly suggested changes which are in master :) (#147)
