### ISSUE TITLE
"Servers" section not appearing in the swagger generated documentation from swagger-jsdoc

### ISSUE THREAD

**Issue by marioalv** [Surnet/swagger-jsdoc#139]
Hi guys.
First of all, thanks for this awesome module. I am learning swagger and your swagger-jsdoc has been very helpful on my learning.

I would like to report a bug: I am using your swagger-jsdoc with openapi 3.0.0 specification. I have included a `servers` section on the `swaggerDefinition` object in my code, but I do not see this `servers` section when the swaggerdocumentation is generated. I am following your examples from here: https://www.npmjs.com/package/swagger-jsdoc

Am I doing something wrong?. Can you please help me?.

I am attaching the files I am using on my project:
- the swagger.js controller, which has the `swaggerDefinition` object that is used to generate the documentation. Note that I had to attach the file as swagger.txt because github does not let me attach js files
- a screenshot of the generated swagger documentation on my localhost, from the swagger.js file and the `swaggerDefinition` object
- a screenshot of the generated swagger documentation from the site https://editor.swagger.io/ . Note that I just copy / paste the json object on `swaggerDefinition` into the editor on https://editor.swagger.io/ and that's the resulting documenation.

Any help will be greatly appreciated.

[swagger.txt](https://github.com/Surnet/swagger-jsdoc/files/2462668/swagger.txt)

![screen shot 2018-10-09 at 6 02 48 pm](https://user-images.githubusercontent.com/411001/46706307-fa7ebe80-cbf0-11e8-858d-5de76d7a119d.png)

![screen shot 2018-10-09 at 6 03 08 pm](https://user-images.githubusercontent.com/411001/46706306-fa7ebe80-cbf0-11e8-956c-8087489cd085.png)

**Comment by marioalv** [comment]
Edit: I solved this bug by deleting the `node_modules` folder and then executing the `npm install` command again. Now the `Servers` section is appearing on the generated swagger documentation.

Thanks!.

**Comment by kalinchernev** [comment]
Thanks for sharing @marioalv !
