### ISSUE TITLE
Reference to components in other file

### ISSUE THREAD

**Issue by lvndry** [Surnet/swagger-jsdoc#142]
Hi,

I would like to make a reference to a component `Adress` in several files.
But it seems like `$ref: '../file.js#components/Adress'` do not work when I use it

**Comment by kalinchernev** [comment]
Could you please share at least a few files with your example so that I can try it without spending hours guessing?

**Comment by lvndry** [comment]
I fixed the problem

**Comment by kalinchernev** [comment]
@lvndry thanks for following up and closing the issue.
If you could share your solution, this will enable other users having similar questions and searching the issue queue to solve the issue, so please do share what was the issue and how you solved it?

**Comment by lvndry** [comment]
The problem was that I add some generic definitions that I wanted to use for different type of users, eg: `Address`, `Identity` so I wanted to create these definitions so that I just have to make a reference to them when needed.
The solution to this is to make sure that in the apis options you go through every file there may be a swagger definition for example like this
 ```
const options = {
	swaggerDefinition,
	apis: ['./src/**/*.js'],
};
``` 
and also make sure that when you make a reference you don't forget to the quotation marks
`$ref: '#/definitions/Address'`
