### ISSUE TITLE
how to write mixed field type

### ISSUE THREAD

**Issue by SensitiveMix** [Surnet/swagger-jsdoc#149]
https://swagger.io/docs/specification/data-models/data-types/#any

**Comment by SensitiveMix** [comment]
![image](https://user-images.githubusercontent.com/16094680/49572923-c2d58e00-f977-11e8-9d02-3f426d150aaa.png)

**Comment by nekdolan** [comment]
This does not work `YAMLSemanticError: Map keys must be unique; "type" is repeated `
