### ISSUE TITLE
Typescript - No endpoints  are being shows.

### ISSUE THREAD

**Issue by KayHS** [Surnet/swagger-jsdoc#150]
Hi,

I am not able to get this working with typescript. Although the swagger app loads, no endpoints are being displayed when i load the /docs url.

**Config**

src/module/swagger.ts

```
    import swaggerJSDoc from "swagger-jsdoc";

    const swaggerDefinition = {
            info: {
                title: "REST API for my App", // Title of the documentation
                version: "1.0.0", // Version of the app
                description: "This is the REST API for my product", // short description of the app
            },
            host: "localhost:3000", // the host or url of the app
            basePath: "/api", // the basepath of your endpoint
        };

        // options for the swagger docs
        const options = {
            // import swaggerDefinitions
            swaggerDefinition,
            explorer: true,

            // path to the API docs
            apis: ["./../app/v2/**/*.ts"],
        };
        // initialize swagger-jsdoc
        const swaggerSpec = swaggerJSDoc(options);

```

**App**

src/app.ts

` this.app.use("/docs", swaggerUi.serve, swaggerUi.setup(swaggerSpec));`

**Code**

src/app/v2/instance/instance.controller.ts

```
   /**
     * @swagger
     *
     * /login:
     *   post:
     *     description: Login to the application
     *     produces:
     *       - application/json
     *     parameters:
     *       - name: username
     *         description: Username to use for login.
     *         in: formData
     *         required: true
     *         type: string
     *       - name: password
     *         description: User's password.
     *         in: formData
     *         required: true
     *         type: string
     *     responses:
     *       200:
     *         description: login
     */

    public async login(req: Request, res: Response): Promise<any> {
       return res.status(200).json({}); 
    }

```

Now when i navigate to `http://0.0.0.0:3002/docs/` i should expect a login endpoint. However swagger documentation loads BUT with no endpoints returning me a msg "No operations defined in spec!"

Something to note my TS gets compiled to JS in a /build folder. To start my app i doing  `npm run serve` on the /build/index.js file.

**Comment by KayHS** [comment]
So i fixed this by updating my config

 from
`apis: ["./../app/v2/**/*.ts"],`

 To

`apis: ["**/*.ts"]`

**Comment by kalinchernev** [comment]
@KayHS thank you for following up and sharing your fix!

**Comment by jnystrom** [comment]
This does not move the jsdoc swagger comments to the js files.  Is there a way to do this with typescript?  I do not push my ts files to dev or prod environments.

**Comment by kalinchernev** [comment]
@jnystrom I am not sure I understand your question. The main idea of using swagger-jsdoc is to keep the swagger spec as close as possible to production code. If you want to create and maintain swagger specification without putting it in annotations, you can simply write a `.yml` or `.json` spec directly using the [swagger editor](https://editor.swagger.io/), for example.

**Comment by dmaksimovic** [comment]
@kalinchernev What @jnystrom meant, I think, and what I also have as a problem currently, is that once I build the project and deliver it to prod, source files don't go with it (*.ts). So when the app is run on the target env, it searches around and doesn't find anything matching the filter, thus the /doc page is empty, i.e. there are no endpoints displayed. Delivering source files is an obvious problem, so wondering how can it be done without it.

**Comment by kalinchernev** [comment]
@dmaksimovic I see the problem better now! :)

First idea: update the regular expression from `apis: ["**/*.ts"]` to `apis: ["**/*.{ts,js"]` or if you could even be more specific to save some time for the matcher like `src/specia/annotated/code/**/*.{ts,js}` The goal in this case is to allow for `.ts` in development and `.js` in production. Or whatever other format you target after compilation.

Second idea: use environment variables. For example `apis: process.env.NODE_ENV === 'production' ? ["**/*.js"] : ["**/*.ts"]`. The goal here is to change matching pattern depending on your current environment.

**Comment by dmaksimovic** [comment]
Thanks for sharing your thoughts. If that would be the setup, the build process would need to assure that the generated .js files retain the swagger comments. Probably there is a webpack plugin which can support that (even though it would keep all comments, not just Swagger), but I'm wondering if the swagger-jsdoc could support build-time bundling of the docs instead? Perhaps a separate webpack-plugin could be written, to avoid implementing it as part of the library?

**Comment by kalinchernev** [comment]
There are 2 community webpack plugins: https://github.com/Surnet/swagger-jsdoc#webpack-integration

Please check if they cover your use case. Checking the compiler options, seems like it's not removing comments by default by the way https://www.typescriptlang.org/v2/en/tsconfig#removeComments so the annotations should theoretically end up in production code to server as a base for the documentation

Though, thinking about the problem a bit more globally, I wouldn't go for doing work on production. Instead, try to find a way to run the swagger-jsdoc on pre-production hook somehow and commit the specification directly instead of building it later.

**Comment by dmaksimovic** [comment]
Thanks for letting me know of the options, really appreciated. I think I'll go for the webpack plugin and see from there.

**Comment by Slava-Ini** [comment]
Had the same issue, spent several hours figuring it out , [this](https://github.com/Surnet/swagger-jsdoc/issues/274) helped me. 
Turns out if you close your jsdoc multiline comment like `* */` or `*/` it works fine, but if you go `**/` it doesn't work. 
Pretty frustrating taking into account that the error message is not even close to pointing it out.
