### ISSUE TITLE
basePath not working

### ISSUE THREAD

**Issue by AlexanderKaran** [Surnet/swagger-jsdoc#159]
Hi Guys

Currently using swagger-ui-express and swagger-jsdoc for some reason my options for base path does not override in my generated docs. For example lets says host is localhost:300 and basePath if /api/v1 in the docs the basePath is not there so when trying out the code it fails.

Here is my code

`
const swaggerJsdoc = require("swagger-jsdoc");
const swaggerUi = require("swagger-ui-express");

// Generate API docs from JSON
const options = {
  swaggerDefinition: {
    info: {
      title: "ClimateClever Schools API",
      version: "1.0.0",
      description: "NodeJS and Express API running in Docker Swarm"
    }
  },
  host: `localhost:3000/`,
  basePath: `api/v1`,
  apis: ["./Routes/Auth/*.js", "./Models/User/swagger.js"]
};
const specs = swaggerJsdoc(options);
router.use("/api-docs", swaggerUi.serve, swaggerUi.setup(specs));
`

<img width="1440" alt="Screen Shot 2019-04-29 at 1 34 08 pm" src="https://user-images.githubusercontent.com/47707063/56877864-810ec680-6a83-11e9-84ca-6b1aa13f3024.png">

**Comment by AlexanderKaran** [comment]
I realised my basePath and host needed to be inside the swaggerDefinition. Got to laugh at yourself sometimes

**Comment by kalinchernev** [comment]
@AlexanderKaran thanks for following up and closing the issue! :)
