### ISSUE TITLE
I can't understand how to use requestBody 

### ISSUE THREAD

**Issue by GBora** [Surnet/swagger-jsdoc#161]
Hello, I have I want to document it is a POST which within the body should accept a json object containing some text, which should look like this:

`{ "text": "do something" }`

I can't figure out how to write the jsdoc to generate the swagger which would allow me to have a form in which to enter objects of that type and test it out.

The best I could come up with looking at the examples and the swagger documentation is in [this gist](https://gist.github.com/GBora/a9a0ba925445ea2e8336434a7cc090e0) as I couldn't get the formatting to work when I tried to paste it here as code.

Which generates an endpoint in the documentation but not one where I can actually enter data for the requests' body so I can test if it works (the code itself works I tested with postman but I need to provide a nice swagger)

![image](https://user-images.githubusercontent.com/3342157/58374698-32056580-7f4b-11e9-9e68-dad9f7fc0085.png)

Sorry for opening an issue but I'm just too stupid none of the examples I found within your repository or in the main swagger docks helped me.

I am also using swagger-ui-express in the library.

**Comment by kalinchernev** [comment]
Hi @GBora I quickly searched in the repo, there's one example of `requestBody` with a string.
Have you checked this [resource](https://swagger.io/docs/specification/describing-request-body/) and particularly [this part of the spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#requestBodyObject)?

On first look, it seems it's possibly this part which is not as concrete/exact as the open api spec:

```
 *                  schema:
 *                      type: object
 *                      required: true
```

**Comment by GBora** [comment]
@kalinchernev Thank you for replying, are you saying that I cannot define a schema within the `@swagger` content and the schema must be in a separate file ?

I admit that almost all of the examples I saw online where with the schema in a separate file, but since I saw a few where the schema was defined inline it seemed possible to me.

As the schema is extremely small in my example I tried to do it inline.

**Comment by kalinchernev** [comment]
Hi @GBora there isn't a difference between inline or separated schema in a file.

I was referring to the structure of how the schema is defined. In particular the part about `type: object`, it seems too general.

If you could share your current setup so that I can try it?

**Comment by GBora** [comment]
@kalinchernev thank you very much the repository is at https://github.com/GBora/rest-helper-server.

The specific file is src/api/todos/ToDosRouter.ts comment starts at line 126.

**Comment by kalinchernev** [comment]
Hi @GBora and thank you for sharing your use case so that I can try it.

The `requestBody` syntax is specific to swagger specification v3+, therefore you'll need to flag that in your definition like this:

```js
const swaggerDefinition = {
  openapi: "3.0.0",
  info: {
    title: "REST-HELPER",
    version: "1.0.0",
    description: "A API to help test out FE frameworks"
  },
  host: `localhost:${port}`,
  basePath: "/api"
};
```

This gives the following in the UI:

![Swagger UI](https://user-images.githubusercontent.com/1923476/58906392-77c4e980-8714-11e9-9bd7-910636649209.png)


Is that what you were referring to?

By the way, I found myself adding this line in the `server.ts`

```js
const port = process.env.PORT || 3000;
```

This way, you can allow for a port, but still have a default one, and use the `port` for short for `process.env.PORT` throughout the whole file.

**Comment by GBora** [comment]
Thank you @kalinchernev , adding the version has fixed things (although I think it has broken some others) I will close this issue now as it's been resolved.

Thank you for the suggestion, I usually add defaults as well, I decided not to on this project but I can't remember my exact reasoning right now.
