### ISSUE TITLE
Use a validator to auto generate body

### ISSUE THREAD

**Issue by Its-Alex** [Surnet/swagger-jsdoc#167]
Do you think of using a validator (like [`joi`](https://github.com/hapijs/joi)) to auto generate body in json file ?

**Comment by kalinchernev** [comment]
@Its-Alex please provide some details in terms of what you would like to achieve, some examples, etc.

**Comment by Its-Alex** [comment]
@kalinchernev I would like to autogenerate swagger from our validation in API.

For example adding [joi-to-swagger](https://www.npmjs.com/package/joi-to-swagger) in swagger-jsdoc.

**Comment by kalinchernev** [comment]
@Its-Alex swagger-jsdoc is working only with comments to swagger specification, it's not to extract information from code as the joi-to-swagger. The latter looks quite nice. Different approach, but if you prefer "code-first" rather than "comments-first" (:D) it will suffice I believe.
