### ISSUE TITLE
Passing Parameter Examples to Postman

### ISSUE THREAD

**Issue by dalexander-trc** [Surnet/swagger-jsdoc#171]
I've read the [OpenAPI Spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#parameterObject) about Parameter Objects, but some of the properties don't import in Postman. I've tried including an _example_ both inside and outside of the schema, so that _your-token-here_ is imported as the value for the _Authorization_ key, but I instead get the schema type in triangle brackets. I'm using OpenAPI v3.0.0.

`parameters:`
`- name: Authorization`
`in: header`
`description: Session authorization token`
`required: true`
`example: 'your-token-here'`
`schema:`
`type: string`

**What I get:**
![image](https://user-images.githubusercontent.com/37082684/63626403-2e23c680-c5c0-11e9-8df7-b9a937ddea60.png)

**What I want:**
![image](https://user-images.githubusercontent.com/37082684/63693620-ccd34180-c7d1-11e9-88d5-07b848d75b69.png)

**Comment by kalinchernev** [comment]
It's hard to help without examples.

Can you start from the point what are you trying to achieve? Is it that you
want to use swagger spec in postman? Do you have a working example of that?

**Comment by dalexander-trc** [comment]
@kalinchernev I've updated my post to include more context. Essentially what I want is to import a specific string into the **Value** portion of a header parameter. All of the configurations I have tried result in either a blank string, or the schema type in triangle brackets.

**Comment by kalinchernev** [comment]
@dalexander-trc thanks for sharing the solution you've found, closing.
