### ISSUE TITLE
components section not getting populated

### ISSUE THREAD

**Issue by lalit117** [Surnet/swagger-jsdoc#172]
I have components section in my each of mongoose model file. i have passed directory path in api key of swagger options. when i am creating final json only single component gets added in json. please let me know what is going wrong.

my conf :
{
   swaggerDefinition: { info: {}, openapi: '3.0.0' },
   apis: [ apiDir, modelDir]
}
thanks in advance

**Comment by kalinchernev** [comment]
Please provide examples of how you define the components.

Please also double check that the variables you have given here are correct
glob patterns which actually find the files which contain the files which
contain the annotations.
