### ISSUE TITLE
AsyncApi support

### ISSUE THREAD

**Issue by Hexenon** [Surnet/swagger-jsdoc#174]
Hello, I'm looking for a solution for AsyncApi 1.0 code-first tool but i haven't see any. I was wondering if we can add this feature to this good tool.
#175

**Comment by Hexenon** [comment]
I created this PR with AsyncApi 1.0.0 support. 

https://github.com/Surnet/swagger-jsdoc/pull/175

**Comment by fmvilas** [comment]
This could be great. Just a minor side note, we're not supporting AsyncAPI 1.x anymore. I recommend you to upgrade to v2 as soon as possible. You have a converter tool that should help: https://github.com/asyncapi/converter.

**Comment by kalinchernev** [comment]
The codebase got refactored quite a lot during the last couple of months.

My thoughts at this stage are that the best would be to fork this swagger-jsdoc and create asyncapi-jsdoc or a similar one.

Although we could have extensive amount of checks and exceptions handling and a shared layer of specification-related operations, it won't be as clean as having a separate project.

Feel free to have a look at the latest version and fork it or continue the work at https://github.com/Zizaco/asyncapi-jsdoc
