### ISSUE TITLE
No support for global security

### ISSUE THREAD

**Issue by c0bra** [Surnet/swagger-jsdoc#177]
According to https://swagger.io/docs/specification/authentication/ you should be able to put a root-level `security` property that defines the security scheme to use by default on all routes

However this module puts that prop under `paths`, maybe because it's not in this array: https://github.com/Surnet/swagger-jsdoc/blob/master/lib/helpers/specification.js#L95

**Comment by kalinchernev** [comment]
Hi @c0bra did you have a look at existing issues? There quite a few people have asked about security in the past: #61, #103, #124, #141

Suggestion: configure through definition object https://github.com/Surnet/swagger-jsdoc/issues/124#issuecomment-410255619

**Comment by c0bra** [comment]
@kalinchernev I don't think I searched through issues because I discovered that the option wasn't being handled while looking at the code directly.

If 5 issues (including this one) have come up so far, maybe it would be good to add a note to the readme for those using openapi 3+?

Thanks for the link to #124; appreciated.
