### ISSUE TITLE
YAML Definition Problem

### ISSUE THREAD

**Issue by alex-stout** [Surnet/swagger-jsdoc#178]
I've been searching around and haven't been able to find a way to use the `swaggerDefinition` as a `.yml` file. I'm using express and the latest version of OpenAPI. 

I've tried passing it in but it seems that this project only parses the `apis` field. Any help is appreciated.

**Comment by kalinchernev** [comment]
@alex-stout you will need to use the library through the CLI in order to be able to pass the definition as `.yml` file. The feature was introduced here: https://github.com/Surnet/swagger-jsdoc/pull/105
