### ISSUE TITLE
GET > Parameters, not working.

### ISSUE THREAD

**Issue by hiaparna** [Surnet/swagger-jsdoc#179]
Hi,
I am not able to use with passing parameters:
![image](https://user-images.githubusercontent.com/10120569/67861353-48f14a80-fadd-11e9-9b78-133e9e08f8c1.png)

Please let me know, if my config is incorrect. Also can you add an example with parameters in the README with other examples.

/**
 *  @swagger
 * /navigation/{name}:
 *      get:
 *      parameters:
 *         - name: name
 *           description: name of the collection
 *           in: path
 *           type: string
 *           required: true
 *      responses:
 *          '200':
 *              description: A successful response
 *
 */

**Comment by Wil-g2** [comment]
I made a example that use "swagger" for api documentation, i hope that help you 
[example Code](https://github.com/Wil-g2/swaggerExample)
