### ISSUE TITLE
how to using bearerAuth input?

### ISSUE THREAD

**Issue by 826327700** [Surnet/swagger-jsdoc#182]
![image](https://user-images.githubusercontent.com/23014381/69912410-f2708680-1463-11ea-8d59-c5c593bc4a07.png)

in my code:
![image](https://user-images.githubusercontent.com/23014381/69912429-2f3c7d80-1464-11ea-985b-410e47726cb4.png)

**Comment by vekvoid** [comment]
You have to use the same key in **security** as in **swaggerDefinition**:
```js
security: [
  {
    Bearer: [] 
  }
] 
```

**Comment by nhh** [comment]
Ive got the same issue.

So far:

![Bildschirmfoto 2020-01-27 um 13 28 11](https://user-images.githubusercontent.com/13472382/73174799-f8ec4900-4108-11ea-8f81-d3d0b958b39c.png)

And usage:

![Bildschirmfoto 2020-01-27 um 13 28 43](https://user-images.githubusercontent.com/13472382/73174802-fab60c80-4108-11ea-9c5e-c9c54c86a45c.png)

What iam missing?

**Comment by kalinchernev** [comment]
Please check this issue which contains several suggestions https://github.com/Surnet/swagger-jsdoc/issues/141

**Comment by kalinchernev** [comment]
Please re-open with additional information if my latest comment does not provide enough help.
