### ISSUE TITLE
How to document for Response Samples

### ISSUE THREAD

**Issue by ekumahost** [Surnet/swagger-jsdoc#185]
I have the following showing 200 response, how do I add the response object sample data to it.
    
     *     responses:
     *       200:
     *         description: hello, creating inventory
     *         sample: {'name': 'john'}
     *         schema:
     *           type: object
     *           properties:
     *             message:
     *               type: string
     *               default: 'retrieved'

**Comment by kalinchernev** [comment]
@ekumahost have you checked this: https://swagger.io/docs/specification/adding-examples/#request-response-bodies?

**Comment by ekumahost** [comment]
thats exactly the syntax am looking for.. God bless.
