### ISSUE TITLE
please add express router support

### ISSUE THREAD

**Issue by dcassiani** [Surnet/swagger-jsdoc#186]
Hi, I tried a lot of things, and noticed that express router support is off the table....

Once I set a JS like this in my apis[ ] param, it swagger-fsdoc won't get it...

`

  module.exports = class SwaggerUiApi {

    constructor(router) {
      this.router = router;
    }

    expose() {
        this.getDocs();
    }

    getDocs() {
        this.router.get(`/docs`, this.isAuthorized, (req,res,next)=>{
            console.log('GET /docs');
            res.status(200).json({
                status: `running!`
              });
        });
    }
  };

`

Is there any support for it?

**Comment by kalinchernev** [comment]
@dcassiani not sure whether I'm understanding your issue, but will try to suggest a solution

The swagger-jsdoc component in your code doesn't care if you're using express server, php code or anything else, as long as there are doblock comments. Docblock comments should have a tag (`@swagger` or `@openapi`) which tells the parser to take the contents of the comments in the docblocks and compiles the swagger specification.

Actually, the oldest example is using express https://github.com/Surnet/swagger-jsdoc/tree/master/example/v2

**Comment by dcassiani** [comment]
I see, thanks.

What I meant was that I thought that swagger-jsdoc had the ability to self discover and document express routers like these:

```
    this.app = express();
    this.router = express.Router();

...

  viewDiscountManagementList() {
    this.router.get(`/offers/discounts/management`, (req, res, next) => {
      const discountType = req.query.discountType;
...

```
