### ISSUE TITLE
Parsering the keyword 'properties'

### ISSUE THREAD

**Issue by petrodstrcil** [Surnet/swagger-jsdoc#187]
I have property with name 'properties' in components object. This is keyword in schema definitions of swagger. Swagger parser did not interpret this keyword well.

```
  GettingClass:
    type: object
    properties:
      serviceid:
        type: integer
      pending_properties:
        $ref: '#/definitions/ModemClass'
      properties: 
        $ref: '#/definitions/ModemClass'
```

**Comment by kalinchernev** [comment]
Can you maybe share what behavior you expect and what is the one you're getting?

**Comment by petrodstrcil** [comment]
Thanks you for your reply
In the model I got this result:

`
GettingClass{
serviceid:	integer
pending_properties:	Structure of arguments as specified in ModemClass{...}
properties:	

}`

I have expected

`
GettingClass{
serviceid:	integer
pending_properties:	Structure of arguments as specified in ModemClass{...}
properties:	Structure of arguments as specified in ModemClass{...}

}`

The problem is in keywords properties. That is use in my code twice. One is in define and others is name of properties.

` GettingClass:

    type: object
    **properties**:
      serviceid:
        type: integer
      pending_properties:
        $ref: '#/definitions/ModemClass'
      **properties**: 
        $ref: '#/definitions/ModemClass'
`

**Comment by kalinchernev** [comment]
@petrodstrcil same code is not enough for me to reproduce the issue.
Skimming through, seems like an issue of conflicting naming, i.e. "properties". It is a fixed keyword of the specification (like reserved keyword) https://swagger.io/docs/specification/data-models/data-types/#object

I'd suggest you rename your field as I don't imagine how it'll be possible add an exception to handle edge cases of conflicting fields naming on the parser side.

Also, the parser itself is a separate project https://www.npmjs.com/package/swagger-parser which will be the place to address the edge case if refactoring is not possible.

**Comment by petrodstrcil** [comment]
@kalinchernev I have to apologize. The problem was not in your package.
I observed that the error is in another package. The question is out of the box. Thank you for your understanding

**Comment by kalinchernev** [comment]
@petrodstrcil thanks for coming back on this and closing it!
