### ISSUE TITLE
Feature request: options.apis allows globs in addition to full file paths

### ISSUE THREAD

**Issue by jonboiser** [Surnet/swagger-jsdoc#19]
This would be useful for projects that have lots routes/controllers broken up into many files. Also, when a new route module is introduced to the project, we will not need to add its path to the array.

Example:

```
var swaggerJSDoc = require('swagger-jsdoc');

var options = {
  swaggerDefinition: {
    info: {
      title: 'Hello World', // Title (required)
      version: '1.0.0', // Version (required)
    },
  },
  apis: ['./routes/*.js'], // Path to the API docs
};

// Initialize swagger-jsdoc -> returns validated swagger spec in json format
var swaggerSpec = swaggerJSDoc(options);
```

If this would be a useful addition, I would be happy to submit a PR.

**Comment by chdanielmueller** [comment]
Hi @jonboiser 

I like this idea.
A implementation in swagger-jsdoc would be cool.

I'm using a glob function myself for generating this.
May this gives you some ideas.

```javascript
var glob = require('glob');

function(globPatterns, removeRoot) {
  // For context switching
  var _this = this;

  // URL paths regex
  var urlRegex = new RegExp('^(?:[a-z]+:)?\/\/', 'i');

  // The output array
  var output = [];

  // If glob pattern is array so we use each pattern in a recursive way, otherwise we use glob
  if (_.isArray(globPatterns)) {
    globPatterns.forEach(function(globPattern) {
      output = _.union(output, _this.getGlobbedFiles(globPattern, removeRoot));
    });
  } else if (_.isString(globPatterns)) {
    if (urlRegex.test(globPatterns)) {
      output.push(globPatterns);
    } else {
      var files = glob.sync(globPatterns);
      if (removeRoot) {
        files = files.map(function(file) {
          return file.replace(removeRoot, '');
        });
      }
      output = _.union(output, files);
    }
  }

  return output;
};
```

**Comment by jonboiser** [comment]
Sounds good! I'll start working on it.

**Comment by monk8800** [comment]
Hi @jonboiser when will this feature be released as its something that's quite useful for the current project am working on.

**Comment by jonboiser** [comment]
@monk8800 I've set up a PR implementing the feature. It's actually pretty simple; I just need to expand the test to cover it.

I don't know when it would be released, but it's actually simple enough for you to bring in `glob` into your project and do something similar.

**Comment by chdanielmueller** [comment]
@monk8800: I plan on taking a look at it tomorrow.
I think the changes will be implemented until the end of this week.

**Comment by monk8800** [comment]
Sounds good
