### ISSUE TITLE
[Feature request] Swagger syntax error checker

### ISSUE THREAD

**Issue by tuanlc** [Surnet/swagger-jsdoc#190]
Hello all,
I'm encountering an issue. I success to generate the swagger doc even the doc contains a syntax error. So, the generated doc cannot display correctly.
![Screenshot_2020-03-13_10-38-46](https://user-images.githubusercontent.com/7950991/76587558-e1311e80-6516-11ea-82d7-6d09c6b3a577.png)

This causes problem when a developer success to generate doc and he does not check the displaying of the doc. So, he does not know that he breaks the API documentation page until customers, PO, developers read the doc and see the error.

I don't see the options that allow feedback on the syntax error/warning when generating the doc.

Did you encounter the issue? How did you manage that?

Feature request: How about an option to check syntax after generating?

Hope to see your answer soon. Thanks in advance!

**Comment by tuanlc** [comment]
I found the solution: https://www.npmjs.com/package/@apidevtools/swagger-parser

**Comment by kalinchernev** [comment]
Thanks for the follow-up!
