### ISSUE TITLE
need https protocol instaed of http

### ISSUE THREAD

**Issue by Sumon-miazi** [Surnet/swagger-jsdoc#192]
Getting **TypeError: Failed to fetch** for a GET request. the **http** protocol should be **https**. but i can't find anything about how to change http to https.
![DeepinScreenshot_select-area_20200315174031](https://user-images.githubusercontent.com/28239287/76700705-69b0ea00-66e4-11ea-8757-ce30a6505780.png)

**Comment by kalinchernev** [comment]
The protocol is part of `host` you pass to the swagger definition, it's what information you pass regarding your API.

I will close the issue with a suggestion to follow this issue https://github.com/swagger-api/swagger-editor/issues/2077 The issue reported here with the TypeError is part of another project and not the swagger-jsdoc.
