### ISSUE TITLE
Docs for TypeScript Support

### ISSUE THREAD

**Issue by georg-schwarz** [Surnet/swagger-jsdoc#194]
Hi together,

I just started using swagger-jsdoc in my nodejs project using Typescript. It was kind of hard to figure out how to use it due to the transpilation process involved.

There are a few workarounds necessary to make it work:
* apis [...] has to point to files in the `/dist` directory due to the transpilation process
* Annotations (in the comments) to model classes are lost in the transpilation process (maybe that also is configurable?). My workaround is adding a dummy function doing nothing but being annotated with the information to the model class. This makes sure that the annotations make it into the `dist` directory.

Took me a while to get it working, so I would like to share with others. Just tell me where to put it :)
Maybe into `docs/typescript` directory?

Note: there is no auto-generation of the information from model classes involved in this workaround. Just using plain annotations. 

Cheers,
Georg

**Comment by kalinchernev** [comment]
Hi @georg-schwarz thank you for the suggestion!
The main README file is a good candidate to have guidance on typescript usage. Maybe right after the CLI section https://github.com/Surnet/swagger-jsdoc#cli and before the https://github.com/Surnet/swagger-jsdoc#reporting-issues

If you are ready to spend some more time to boostrap a special section related to typescript, could you review https://github.com/Surnet/swagger-jsdoc/search?q=typescript&type=Issues previous discussions and make a short FAQ? I feel like there will be recurring topics such as reusing interfaces and definitions together with the transpilation topic.

**Comment by Metroxe** [comment]
Sorry if I misunderstood how the compiling works, but it library doesn't go through direct logic or the js itself (correct me if i'm wrong), it simply looks for comments.

If this is the case, then why not just compile the ts in the first place, could you not just tell the jsdoc to look directly at the ts files?

From your example in your pull request, you are looking at the dist directory. Why not just tell it to look at the ts files in the src.

```
apis: [
	"src/index.ts",            // REST API
	"src/api/example-api.ts",  // REST API
	"src/models/example.ts"    // model
]
```

This way you wouldn't need the empty function for your models either. I tried running it and outputted to yml and got...

```yml
info:
  title: Scheduler API
  version: 1.0.0
  description: TypeScript Example API
host: 'localhost:8080'
basePath: /
swagger: '2.0'
paths:
  /:
    get:
      description: Alive ping
      responses:
        '200':
          description: I am alive!
          schema:
            type: string
  /version:
    get:
      description: Current API version
      responses:
        '200':
          description: Returns the current API version (semantic versioning).
          schema:
            type: string
  /example:
    get:
      description: Get an example.
      produces:
        - application/json
      responses:
        '200':
          description: The example.
          schema:
            type: array
            items:
              $ref: '#/definitions/Example'
definitions:
  Example:
    type: object
    required:
      - id
      - description
    properties:
      id:
        type: number
      description:
        type: string
      parameters:
        type: array
        items:
          $ref: '#/definitions/ExammpleParameter'
  ExammpleParameter:
    type: object
    required:
      - type
      - value
    properties:
      type:
        type: string
      value:
        type: string
responses: {}
parameters: {}
securityDefinitions: {}
tags: []
``` 

If this is the case, is there really anything that would need to change from a regular implementation using js to support ts? I only found this library yesterday and haven't used it extensively yet, so please correct me if I'm overlooking something.

**Comment by georg-schwarz** [comment]
So, it depends I think.

In my use case, generating these files at runtime, I need them to point to the js files since the ts files are not delivered to the runtime environment.

If you just use the CLI to generate once, he ts files should be perfectly fine.

**Comment by kalinchernev** [comment]
Just to confirm @Metroxe 's understanding: the swagger-jsdoc tool parses no-matter-what source code and only cares about the comments.

**Comment by mxvin** [comment]
Yeah, you must point it on `dist/api/*.js` instead your project structure on `src/api/*.ts`

**Comment by kalinchernev** [comment]
Added a document outlining typescript questions https://github.com/Surnet/swagger-jsdoc/blob/master/docs/TYPESCRIPT.md
