### ISSUE TITLE
basePath not working

### ISSUE THREAD

**Issue by varmeh** [Surnet/swagger-jsdoc#201]
Issue: basePath not working.

Used `swagger-jsdoc` with `swagger-ui-express`.

configuration used:

```
    const swaggerDefinition = {
		openapi: '3.0.3',
		info: {
			title: 'Stockal API',
			version: '1.0.0'
		},
		basePath: '/api'
	}

	const swaggerOptions = {
		swaggerDefinition,
		apis: ['**/*.routes.js']
	}
```

Instead of making calls to `http://localhost:3000/api/home`, calls are redirected to `http://localhost:3000/home`.

Swagger.json generated by jsdoc:
```
{
  "openapi": "3.0.3",
  "info": {
    "title": "API",
    "version": "1.0.0",
    "contact": {
      "name": "Support",
      "email": "test@test.com"
    }
  },
  "basePath": "/api",
  "paths": {
    "/home": {
      "get": {
        "description": "Home message",
        "produces": "application/json",
        "responses": {
          "200": {
            "description": "message",
            "schema": {
              "type": "object"
            }
          }
        }
      }
    }
  },
  "components": {},
  "tags": []
}
```

Please help.

**Comment by hubgit** [comment]
Use `servers` instead:

```
       const swaggerDefinition = {
		openapi: '3.0.3',
		info: {
			title: 'Stockal API',
			version: '1.0.0'
		},
		servers: [{ url: '/api' }]
	}
```

https://swagger.io/docs/specification/api-host-and-base-path/

**Comment by akshay-nm** [comment]
I am still facing the same issue. 
```
const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Poplink API', 
      version: '0.1.0',
    },
  },
  servers: [{ url: '/api/v1' }],
  apis: [path.join(appDir, "/routes/**/*.js")],
}
```

my request URL is still: `http://localhost:4000/users` when I am hitting the `/users` endpoint.

**Comment by akshay-nm** [comment]
I am still facing the same issue. 
```
const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Poplink API', 
      version: '0.1.0',
    },
  },
  servers: [{ url: '/api/v1' }],
  apis: [path.join(appDir, "/routes/**/*.js")],
}
```

my request URL is still: `http://localhost:4000/users` when I am hitting the `/users` endpoint.

Here is the generated swaggerDoc:

```
{
  openapi: '3.0.0',
  info: { title: 'Poplink API', version: '0.1.0' },
  paths: {
    ...
  },
  components: {},
  tags: [
    ...
  ]
}
```

**Comment by akshay-nm** [comment]
ooooo
I noticed, the servers are supposed to be inside the definition... 
Damn...
My bad.


> I am still facing the same issue.
> 
> ```
> const options = {
>   definition: {
>     openapi: '3.0.0',
>     info: {
>       title: 'Poplink API', 
>       version: '0.1.0',
>     },
>   },
>   servers: [{ url: '/api/v1' }],
>   apis: [path.join(appDir, "/routes/**/*.js")],
> }
> ```
> 
> my request URL is still: `http://localhost:4000/users` when I am hitting the `/users` endpoint.
> 
> Here is the generated swaggerDoc:
> 
> ```
> {
>   openapi: '3.0.0',
>   info: { title: 'Poplink API', version: '0.1.0' },
>   paths: {
>     ...
>   },
>   components: {},
>   tags: [
>     ...
>   ]
> }
> ```

**Comment by kalinchernev** [comment]
Closing the issue and leaving a link to the object definition spec https://swagger.io/specification/#oasObject
