### ISSUE TITLE
EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by Nguyenkhanh98** [Surnet/swagger-jsdoc#202]
Hi everyone, I got this error when  run the command line to generate swagger file. The full error is
![Capture](https://user-images.githubusercontent.com/37452723/83852570-322f6800-a73e-11ea-973d-37915d964a26.PNG)
. 

The error disappear and working correct when I remove 'mysql' dependency. And I see that another module is in the same like this is 'jest'.  

You can easy to reach this error by install swagger-jsdoc with one of 'mysql' and 'jest', then run the cmd to generate swagger file.

Thanks

**Comment by kalinchernev** [comment]
EISDIR means that the target of the operation is a directory in reality but that the expected filetype of the target is something other than a directory.

If the issue still persists, please create a sample repo where the error occurs in a repeatable manner.

Thanks
