### ISSUE TITLE
CustomCSS option

### ISSUE THREAD

**Issue by Svkiyo** [Surnet/swagger-jsdoc#209]
Hi,

There is no way to add customCss as written in [swagger-ui-express](https://www.npmjs.com/package/swagger-ui-express) doc ?

```
var options = {
  customCss: '.swagger-ui .topbar { display: none }'
};
```

Because with the following code isn't working at all.

```
var options = {
    swaggerDefinition: {
        info: {
            title: 'backend',
            version: '1.0.0',
            description: 'API'
        },
        customCss: '.swagger-ui .topbar { display: none }'
        basePath: '/api',
    },
    apis: ['./route/*.js']
};

const specs = swaggerJSDoc(options);
```

Thanks for helping

**Comment by kalinchernev** [comment]
swagger-jsdoc collects, combines and parses yaml information in jsdoc comments and yaml files. In short, it gives you the `swaggerDocument` mentioned in swagger-ui-express.

Your question related to how the specification is used is either to be asked at https://github.com/scottie1984/swagger-ui-express or https://github.com/swagger-api/swagger-ui
You can of course
