### ISSUE TITLE
Writing jsdoc in YAML is very difficult with comments

### ISSUE THREAD

**Issue by dilipkumar2k6** [Surnet/swagger-jsdoc#21]
I liked this module however when I tried to use it for my API then it became nightmare as its very difficult to hand code JSDoc in YAML style. Very tough to write valid YAML syntax inside the comments. 

Can I used any other comment format?

**Comment by chdanielmueller** [comment]
Hi @dilipkumar2k6

What format would you prefer to describe the spec with?
I think to write JSON in JSDoc is not very handy to read and it looks a bit missplaced in the documentation.

I am keen to hear about your opinion on this.

- Daniel

**Comment by dilipkumar2k6** [comment]
I would prefer to use pure JSDoc if possible. Writing yaml in comments is very difficult. I found following module useful in terms of writing the docs however quality of generated swagger.yaml is not good.
https://github.com/fsbahman/apidoc-swagger

Still not able to make decision to choose the better approach.

**Comment by fyodorvi** [comment]
@dilipkumar2k6 apidoc-swagger is super buggy, quite useless

**Comment by chdanielmueller** [comment]
Hi @dilipkumar2k6,

As you said by yourself https://github.com/fsbahman/apidoc-swagger uses another approach in documenting the swagger documentation.
It is not the purpose of this package to support all kinds of documentation styles, but one way in a good working manner.

I hope you can decide on one or the other package.

Regards,
Daniel

**Comment by dietergeerts** [comment]
The way to write the swagger docs as yaml inside jsdoc is really not useful, it's hard to maintain, hard to read etc.... I would prefer to use something like apidoc-swagger, but better, where you also can use normal jsdoc typedefs as return types etc...

**Comment by kalinchernev** [comment]
Since [1.9.0](https://github.com/Surnet/swagger-jsdoc/releases/tag/v1.9.0) you can use external files to which are included in your specification.
