### ISSUE TITLE
Can developers generate clients/stubs if we use swagger-jsdoc?

### ISSUE THREAD

**Issue by cawoodm** [Surnet/swagger-jsdoc#210]
We have used swagger-jsdoc and swagger-ui-express to make a nice Swagger UI explaining our API. The question is how can developers who use our API generate a client stub (e.g. in Java)?

As explained [here](https://fizzylogic.nl/2018/09/26/learn-how-to-quickly-generate-rest-clients-from-swagger-files) the developer needs to "type in the URL of the swagger endpoint you want to load". It's not clear what this endpoint is.

Alternatively can we access the OpenAPI description of our API as a JSON object like this?

```
{
    "openapi": "3.0.3",
    "info": {
      "description": "Parts Service",
      "version": "1.0.1",
      "title": "parts"
    },
    "paths": {
      "/parts/ping": {
        "get": {
...
```

**Comment by kalinchernev** [comment]
@cawoodm swagger-jsdoc as a tool helps you generate Open API specification. The generated YAML or JSON specification can be delivered through a server like node http server shown [here](https://github.com/Surnet/swagger-jsdoc/tree/master/example/v2). The specification file can be generated as a physical file by the [CLI](https://github.com/Surnet/swagger-jsdoc/blob/master/docs/CLI.md).

"type in the URL of the swagger endpoint you want to load" is the URL of the place you put the specification at. This can be even a Github repo (raw file address) or even a gist. Doesn't really matter as long you put the file somewhere online and you provide a link to this place.

**Comment by cawoodm** [comment]
Thanks guys, this is exactly what we were looking for!

```javascript
  const swaggerUi = require('swagger-ui-express');
  const swaggerJsDoc = require('swagger-jsdoc')({
    definition: {
      openapi: '3.0.3',
      info: {
        description: 'Service (<a href="./api-docs.json">JSON</a>)',
        version: config.npm_package_version,
        title: 'Parts Microservice',
      },
    },
    apis: ['./src/routes/*.js'],
  });
  app.use('/', swaggerUi.serve);
  app.get('/', swaggerUi.setup(swaggerJsDoc));
  app.get('/api-docs.json', (req, res) => {
    res.setHeader('Content-Type', 'application/json');
    res.send(swaggerJsDoc);
  });
```
