### ISSUE TITLE
swagger-jsdoc ignores comment

### ISSUE THREAD

**Issue by pchans** [Surnet/swagger-jsdoc#216]
Hello,

I've been working with swagger-jsdoc for two weeks now and I am really happy about it but I've got a problem that I feel like I can't resolve.
I have a file with more than a hundred of @swagger comments and when I create my .yaml with the CLI all of them work except one. 

If I intentionally do a syntax error on this code block, swagger-jsdoc notices me so it doesn't "ignore" the comment.

Moreover, when I put this exact comment in another file and run swagger-jsdoc, it works for no reason...

The comment : (sorry it's written in French), I've triple checked the links classes/classes/atelier.html and they are totally fine.
Looking for your help.

/** 
 * @swagger
 * /api/bibliotheque/atelier/update/:key :
 *   patch:
 *     tags:
 *       - Atelier
 *     summary : Mise à jour d'un atelier
 *     description: 
 *     produces:
 *       - application/json
 *     parameters:
 *       - name: :key
 *         description: Code atelier 
 *         in: query
 *         required: false
 *       - name: atelier
 *         description: Propriétés modifiées uniquement.
 *         in: body
 *         required: true
 *         schema:
 *           properties :
 *            Atelier:
 *             type: object
 *             externalDocs:
 *               description: Classe Atelier
 *               url : classes/classes/atelier.html
 *     responses:
 *       200:
 *         description: Atelier mis à jour
 *         schema : 
 *           properties :
 *            Atelier:
 *             type: object
 *             externalDocs:
 *               description: Classe atelier
 *               url : classes/classes/atelier.html
 *       404:
 *         description: Code non trouvé
 *       500:
 *         description: Erreur serveur
*/

**Comment by pchans** [comment]
![image](https://user-images.githubusercontent.com/72491990/95304598-2aff9e80-0885-11eb-9cb5-82f348bee495.png)

**Comment by kalinchernev** [comment]
Have you tried using the lowercase `@swagger`? I see `@Swagger` which is not matched by design at the moment.

**Comment by pchans** [comment]
Yes, I used @swagger with no capital letter. The real bizarre thing is that if I copy paste this exact comment lower in the file (I found something that we could call a "breakpoint") under a distinct line (number 1051), then this comment is translated in the .yaml file

**Comment by kalinchernev** [comment]
@pchans that's indeed a strange behavior when output changes based on a given area of code. 
Could you please create either a [gist](https://gist.github.com/) or paste part of your code with a [block](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) or [details](https://gist.github.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f) in order for me to be able to reproduce this behavior?
