### ISSUE TITLE
npm warning openapi-types@>=7

### ISSUE THREAD

**Issue by wottpal** [Surnet/swagger-jsdoc#218]
Is anybody else getting this warning? Should I install this package manually? Why is it not done automatically? Thanks!

```
npm WARN @apidevtools/swagger-parser@10.0.2 requires a peer of openapi-types@>=7 but none is installed. You must install peer dependencies yourself.

❯ npm list @apidevtools/swagger-parser
project@1.0.0
└─┬ swagger-jsdoc@4.2.3
  └─┬ swagger-parser@10.0.2
    └── @apidevtools/swagger-parser@10.0.2 
```

**Comment by Shogobg** [comment]
Yes, you need to install this package manually, as it says in the description.
For your question why it's not automatically installed, you should ask in the repository of swagger-parser why they need swagger parser as peer dependency - the openapi-types is its dependency not swagger-jsdoc's
You can also Google "npm peer dependencies" and read the design behind this - it's an implementation by NPM.

**Comment by kalinchernev** [comment]
The swagger-jsdoc package is currently vanilla node.js and there are no types, thus I don't see a reason to mark it as a peer on this package.

Thanks @Shogobg for the clarification above
