### ISSUE TITLE
Bearer token not being used in OAuth 2 implicit flow.

### ISSUE THREAD

**Issue by husban125** [Surnet/swagger-jsdoc#219]
Hi,

I am trying to use OAuth 2 implicit flow to authenticate. But after authenticating, a JWT token is not used in the header of requests, instead a random 32 character string is used.

![image](https://user-images.githubusercontent.com/10885856/97338039-e4e09e00-1878-11eb-8e07-734e17d72909.png)

I cannot verify were this is coming from.

Swagger JsDoc:

```
import swaggerJSDoc, { Options } from 'swagger-jsdoc';

const options: Options = {
  swaggerDefinition: {
    openapi: '3.0.3',
    info: {
      title: 'Api',
      version: '1.0.0',
    },
    servers: [
      {
        url: '/'
      }
    ],
    components: {
      securitySchemes: {
        Auth0: {
          type: 'oauth2',
          flows: {
            implicit: {
              authorizationUrl: 'https://url.com/authorize',
              scopes: {
                audience: 'https://url.com'
              }
            }
          }
        }
      }
    },
    security: [
      {
        "Auth0": []
      }
    ]
  },
  apis: ["./controllers/*"]
};

const swaggerSpec = swaggerJSDoc(options);

export default swaggerSpec;
```

thanks

**Comment by kalinchernev** [comment]
Hi, I also don't know where this behavior might come from. It's not from swagger-jsdoc for sure as it only works with your annotations, not the logic behind the API.
Best to check the logic behind the controllers would be my suggestion.
