### ISSUE TITLE
Add support for Swagger tags

### ISSUE THREAD

**Issue by simast** [Surnet/swagger-jsdoc#22]
This does not seem to work:

```
/**
 * @swagger
 * tag:
 * ...
 */
```

Would be great if this syntax was supported (similar to definitions/parameters/etc).

**Comment by chdanielmueller** [comment]
Hi @simast,

Would you like to implement this by yourself?

**Comment by simast** [comment]
@chdanielmueller Sure, I will take a shot at this!
