### ISSUE TITLE
Ignores openapi spec in yaml

### ISSUE THREAD

**Issue by dopecodez** [Surnet/swagger-jsdoc#221]
## Problem

So, I have a yaml document like so :
```
openapi: '3.0.0'
paths:
  /authors:
    post:
      summary: End point to create a author
      tags:
        - Author
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthorCreation"
      description: It enables a you to create a author.
      responses:
        "200":
          description: Success object with created author
```
It also has a schema being defined as 
```
components:
  schemas:
    AuthorCreation:
      type: object
      required:
        - authorName
      properties:
        authorName:
          type: string
```

When i try loading this file with swagger-jsdoc, and try to render it using `swagger-ui-express` it keeps showing the swagger ui without the models available which means no post requests are possible.

## Solution
I tried to print the output after `const swaggerSpec = swaggerJSDoc(options);`  and found that it still outputs `swagger:2.0` in the JSON that's produced. I fixed the issue by manually deleting this key and adding a `openapi:3.0.0` key to the `swaggerSpec` object.

## Expectation
When explicitly specifying open api version in the yaml file, it should be preserved when the conversion to JSON happens.

**Comment by kalinchernev** [comment]
Please see documentation and examples for the so called `swaggerDefinition` object. The version should be passed via the `options`, not the path definitions.

**Comment by dopecodez** [comment]
```
const options = {
  definition: {
    openapi: '3.0.0', // Specification (optional, defaults to swagger: '2.0')
    info: {
      title: 'Hello World', // Title (required)
      version: '1.0.0', // Version (required)
    },
  },
  // Path to the API docs
  apis: ['./routes.js'],
};
```
Yea, I noticed that when I went through the examples like you suggested. It looks good, but I really think we should be putting it at the README.MD page so its more accessible.

Also, can we think about a override for that option in case its specified in the `.yaml` file? We'll look for the spec in options and set that if present, and if the spec exists in the `.yaml` file, it can act like a overload of the same options.

I will take a look at it in case its a feature you think would be useful.

**Comment by kalinchernev** [comment]
Hi @dopecodez thanks for confirming you solved your case.
There is no plan currently to change how spec versioning works. You can use the same definition file in your case too: split into 2 files for the 2 versions and specify different globs in the apis property. You will have to run the parsing twice of course.
