### ISSUE TITLE
mix jsdoc and yml files

### ISSUE THREAD

**Issue by sibelius** [Surnet/swagger-jsdoc#223]
This package is great, thanks for this

Does it make sense to support both jsdoc and pure yml definitions?

I could have something like this inside my node routes

```jsx
/**
 * @openapi
 * /api/getUser:
 *   get:
*/
```

or also having a colocated file besides `getUser.ts` like `getUser.yml`

getUser.yml
```
/api/getUser
   get:
```

**Comment by kalinchernev** [comment]
Hi @sibelius could you please check https://github.com/Surnet/swagger-jsdoc/issues/107#issuecomment-421765569
It is possible to feed in yaml files for definition and files which are to be added to the final spec

**Comment by sibelius** [comment]
can we also support `.yml` as a .glob ?

like this

`swagger-jsdoc.js -d src/**/*.yaml`

**Comment by sibelius** [comment]
`yarn swagger-jsdoc -d src/swagger/config.js 'src/**/*.yml'`

works

tks
