### ISSUE TITLE
The POST request in Swagger-UI carries no body data

### ISSUE THREAD

**Issue by qian-fei** [Surnet/swagger-jsdoc#225]
my parameter configuration:

*     parameters:
 *       - name: user
 *         in:  body
 *         required: true
 *         type: string
 *         schema:
 *           type: object
 *           required:
 *             - sms_code
 *             - password
 *             - mobile
 *           properties:
 *             sms_code:
 *               type: string
 *             mobile:
 *               type: string
 *             password:
 *               type: string

**Comment by kalinchernev** [comment]
Please report issue in its corresponding queue: https://github.com/swagger-api/swagger-ui/issues
