### ISSUE TITLE
 From routes to a single file yaml or json

### ISSUE THREAD

**Issue by sminodonte** [Surnet/swagger-jsdoc#226]
Is it possible create a single file yaml o json for the entire application from the routes:

I could have something like this inside my routes

/**
 * @openapi
 * /api/...:
 *   get:
*/

Thanks

**Comment by kalinchernev** [comment]
Have you tried making it? :)
Should be possible. Any files you input are combined in the end specification result. If you have one file, it shouldn't be having an edge case scenario
