### ISSUE TITLE
x-webhooks support

### ISSUE THREAD

**Issue by syJSdev** [Surnet/swagger-jsdoc#228]
x-webhooks is not supported.
Current
[Current Result](https://prntscr.com/vony9k)
Expected
[Expected Result](https://prntscr.com/vonxdo)

**Comment by kalinchernev** [comment]
@syJSdev thanks for bringing up the subject.

In a separate issue, I've added this line https://github.com/Surnet/swagger-jsdoc/pull/227/files#diff-44c7f1f37bbea27c61ce33a9fb04b1dcb8eb1877923faa4517b77222b9179294R107 which will keep ignoring extensions.

I wasn't sure what to do with these properties back then, but now having this discussion it's worth re-opening.

Could you please share more information about these x-webhooks?

**Comment by syJSdev** [comment]
I am using `redoc-cli` for documenting.
And generate spec.json with `swagger-jsdoc`.

Here is the ref doc about the x-webhoooks.
https://github.com/OAI/OpenAPI-Specification/blob/master/proposals/002_Webhooks.md#proposed-solution

And here is the demo of redoc which using x-webhooks.
https://redocly.github.io/redoc/#operation/newPet
https://redocly.github.io/redoc/openapi.yaml

**Comment by kalinchernev** [comment]
Hi @syJSdev I just released `swagger-jsdoc@6.0.0-rc.5` which supports this extension and will put it in the root as pointed out in the reference redoc spec and as outlined in the proposal.

Thank you for suggesting this change and providing useful background information!
