### ISSUE TITLE
Como eu faço para definir um prefixo no campo de inserir o Bearer Token.

### ISSUE THREAD

**Issue by rivanbello** [Surnet/swagger-jsdoc#230]
Eu gostaria de deixar definido no input do token o "Bearer" por padrão. 

É possível?

O resultado após eu clicar no botão de authorize seria vir no input o texto "Bearer" definido por padrão, assim eu so colocaria o token.

https://www.linkpicture.com/view.php?img=LPic5fc2f541bd6c2224064170

**Comment by kalinchernev** [comment]
Sorry, but my Spanish too limited to understand the issue. Restarted the studying a few times in high school but never got to have the right teacher.

Please reopen if it's possible to make it in English with as many details as possible.

**Comment by rivanbello** [comment]
I would like to leave no entry defined for "Bearer" by default.

It's possible?

The result after I click on the authorize button would be without entering the text "Bearer" defined by default, so I would then place the token.

https://www.linkpicture.com/view.php?img=LPic5fc2f541bd6c2224064170

@kalinchernev

**Comment by kalinchernev** [comment]
swagger-jsdoc only takes the comments you annotate with the @swagger tag and compiles the specification.
For specification-specifics, you should read the documentation at https://swagger.io/docs/specification/authentication/ and  https://swagger.io/docs/specification/authentication/bearer-authentication/ to see how it's expected

Also, the interface you're showing in the picture is https://swagger.io/tools/swagger-ui/ which is here https://github.com/swagger-api/swagger-ui/issues

Last but not least, as suggested in the landing page, you could browse already closed issues and get suggestions for your issue too based on experience from the past https://github.com/Surnet/swagger-jsdoc/issues/141
