### ISSUE TITLE
Please update docs for oapi3

### ISSUE THREAD

**Issue by JoffrayBillon** [Surnet/swagger-jsdoc#236]
Hi,

Your doc has little problem, actually, it's hybrid between swagger 2 and openapi3, making weird behavior and causing https://github.com/scottie1984/swagger-ui-express being flooded of bug request because they don't read the official swagger docs ^^'

Would be a pleasure to do it for you, later in the week, if I have the time for it :)
Also let me recommand you restoring the old swagger 2 docs right now and making a second one supporting the openapi3 to avoid any confusion.

**Comment by kalinchernev** [comment]
Reading the feedback here, I have no idea what it refers to.

**Comment by JoffrayBillon** [comment]
@kalinchernev I'm talking about [that](https://github.com/Surnet/swagger-jsdoc/blob/master/docs/GETTING-STARTED.md#annotating-source-code) all code annotation are made for swagger 2 for example in oapi3 : 
```
definitions:
```
have been replaced by
```
components:
  schemas:
```
Like specified [here](https://swagger.io/docs/specification/components/#difference)
And also a lot in oasObject definitions but hopefully the doc isn't covering that part and redirect directly to openapi docs

**Comment by kalinchernev** [comment]
I added a new section specifically warning about the default behavior of the library targeting v2.
I also moved the paragraph already pointing out to the mentioned components approach for v3.
