### ISSUE TITLE
regression on v6 on yaml output

### ISSUE THREAD

**Issue by sibelius** [Surnet/swagger-jsdoc#237]
I've generate both .json and .yml files using swagger-jsdoc like this

json generation:
swagger-jsdoc -d ./swaggerConfig.js ./defs/**/*.yml -o api.json

yaml generation
swagger-jsdoc -d ./swaggerConfig.js ./defs/**/*.yml -o api.yml

it worked on v5, and it is outputting .json on api.yml on v6

**Comment by kalinchernev** [comment]
Thank you @sibelius for reporting the regression! It's fixed in 6.0.1
