### ISSUE TITLE
Can swagger-jsdoc be used from CLI

### ISSUE THREAD

**Issue by raphaelokon** [Surnet/swagger-jsdoc#24]
Hi there. 
Thanks for this cool tool. I am wondering if one could use the tool from the command line as well?

**Comment by kalinchernev** [comment]
I'd be happy to help and get my hands on in case it's considered a useful feature by the maintainer.

**Comment by chdanielmueller** [comment]
Hi @kalinchernev,
I think it is a useful feature. Feel free to develop it.
Thanks,
Daniel

**Comment by kalinchernev** [comment]
The issue may be closed as the pull request has been merged.
