### ISSUE TITLE
Wrong output file format

### ISSUE THREAD

**Issue by Iamhashim92** [Surnet/swagger-jsdoc#244]
I am trying to generate output file in `yaml`  format by using this command
`swagger-jsdoc -- -d definition.yaml ./src/create.js -o swagger.yml &>/dev/null`

but it is outputting a wrong file format like this
`"openapi: 3.0.3\ninfo:\n  title: My API\n  version: 1.0.0\n  description: The Project internal API documentation\nservers:\n  - url: http://localhost:3000\n "`

version- `6.0.2`

**Comment by kalinchernev** [comment]
Hi @Iamhashim92, a few questions: 
1) why adding two dashes before definition? i.e. -- + - d
2) why &>/dev/null?

**Comment by Iamhashim92** [comment]
Hi @kalinchernev ,
1- Because i have a script in `package.json` like this `"swagger": "swagger-jsdoc"`.
2- And about `&>/dev/null` to not receive any outputs.
on the end the `&>/dev/null`  does not matter

**Comment by kalinchernev** [comment]
Hi @Iamhashim92 you were right, the issue is not on your part, it's the lib.
I made a few changes https://github.com/Surnet/swagger-jsdoc/pull/245
Do you mind making a review?

**Comment by Iamhashim92** [comment]
Hi @kalinchernev,
Changes looks good to me 🎉. 
I will test the new version and will let you know.

**Comment by kalinchernev** [comment]
@Iamhashim92 the reason i asked for your review is making sure it's ok before publishing it.
You can use test it by changing `swagger-jsdoc` item in `package.json` from a specific version to this

```
"swagger-jsdoc": "Surnet/swagger-jsdoc#fix/yaml-formatting"
```

It's the name of the repo + the branch. Remove previous node_modules forlder, reinstall and test please
