### ISSUE TITLE
v7: Command "swagger-jsdoc" not found.

### ISSUE THREAD

**Issue by damianobarbati** [Surnet/swagger-jsdoc#248]
v7 has cli broken?

```bash
$ node -v
v14.15.5
$ cat package.json| grep '"swagger-jsdoc"'
   "swagger-jsdoc": "^7.0.0-rc.2",

$ yarn swagger-jsdoc
error Command "swagger-jsdoc" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by kalinchernev** [comment]
Hi @damianobarbati please see release notes here https://github.com/Surnet/swagger-jsdoc/releases/tag/v7.0.0-rc.1
It's moved to examples https://github.com/Surnet/swagger-jsdoc/tree/v7/examples/cli and has become a responsibility of the user to create it. I've made a simple example here https://github.com/Surnet/swagger-jsdoc/tree/v7/examples/cli
There are projects like this which have made alternative CLIs too https://github.com/lmammino/swagger-jsdoc-generator
