### ISSUE TITLE
I cant config security definitions

### ISSUE THREAD

**Issue by guifernandez** [Surnet/swagger-jsdoc#25]
I put config securityDefinitions, but still this property is empty.

**Comment by chdanielmueller** [comment]
Please check the following part from the README.md

### Load external definitions 

You can load external definitions or paths after ``swaggerJSDoc()`` function.
```javascript
// Initialize swagger-jsdoc -> returns validated swagger spec in json format
var swaggerSpec = swaggerJSDoc(options);
// load external schema json
swaggerSpec.definitions.in_login = require("config/schemajson/in.login.schema.json");
swaggerSpec.definitions.out_login = require("config/schemajson/out.login.schema.json");
// or set manual paths
swaggerSpec.paths["api/v1/cool"] = {"get" : { ... } }
};
```

**Comment by TopGuo** [comment]
what is 'options'?

**Comment by kalinchernev** [comment]
@TopGuo please follow examples from [previous questions](https://github.com/Surnet/swagger-jsdoc/search?q=security&type=Issues). For instance, #141
