### ISSUE TITLE
JWT Auth Token

### ISSUE THREAD

**Issue by Dave3of5** [Surnet/swagger-jsdoc#251]
**Is your feature request related to a problem? Please describe.**
I have no idea how to get the auth button to appear with the latest version of this lib.

**Describe the solution you'd like**
Documentation on the config to get the auth button to appear with some examples

**Describe alternatives you've considered**
None, maybe this is something in the swagger-ui I use swagger-ui-express

**Additional context**
N/A

**Comment by kalinchernev** [comment]
Hi @Dave3of5 have you maybe checked this one https://github.com/Surnet/swagger-jsdoc/issues/141#issuecomment-441451877

**Comment by daniloab** [comment]
As this has already been resolved in the issue mentioned, we are closing this. Any questions just speak via slack or open a new issue.

slack https://join.slack.com/t/swagger-jsdoc/shared_invite/zt-qlt08dur-coBeh8ZM11VbCZ6J3lzyNA
