### ISSUE TITLE
Presumably incorrect dist-tags on npmjs.com

### ISSUE THREAD

**Issue by dkamyshov** [Surnet/swagger-jsdoc#265]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when `$ yarn upgrade-interactive --latest` suggests installing unstable versions.

**Describe the solution you'd like**

Update the dist-tags so that the latest tag is only used for stable versions. See https://docs.npmjs.com/cli/v6/commands/npm-dist-tag.

**Describe alternatives you've considered**

Updating to the latest stable version manually.

**Additional context**

![image](https://user-images.githubusercontent.com/26835323/116445411-8794cc00-a85e-11eb-8e8d-25087b0c915a.png)

**Comment by daniloab** [comment]
the npm latest version was fixed for the latest one: 6.1.0.

Thanks @dkamyshov for the issue.

You can check here https://www.npmjs.com/package/swagger-jsdoc
