### ISSUE TITLE
rename package name

### ISSUE THREAD

**Issue by sibelius** [Surnet/swagger-jsdoc#269]
This package is awesome and does more than just swagger inside jsdoc

it is more like a general bundler for jsdoc, .json, .yml files to build openapi or asyncapi documentation

what about a new name for it?

openapi-bundler?
documentation-bundler?
api-doc-bundler?

**Comment by chdanielmueller** [comment]
As discussed in the call:
Renaming the Repo and/or the npm package has so many implications and negative impacts on the users that I do not recommend it.
