### ISSUE TITLE
Maintainers wanted

### ISSUE THREAD

**Issue by chdanielmueller** [Surnet/swagger-jsdoc#273]
Hi there,

As @kalinchernev wants to stop maintaining this project we are searching for new maintainers.
I would like to thank him again for his work in this project over the years.
He has maintained the project very well!

@daniloab already stepped up to become a new maintainer of the project and we are searching more.
This spreads the load across more people and allows for collaboration and second opinions.

There is no obligation to provide a certain amount of time.
It shall be used as a opportunity to learn and grow in the open source world.
Ohh and of course if interested I could add a donation link for people to support the maintainers of this package.

If you are interested in becoming a maintainer please comment on this issue, write me a mail or join our Slack chat.
https://join.slack.com/t/swagger-jsdoc/shared_invite/zt-qlt08dur-coBeh8ZM11VbCZ6J3lzyNA
I am available for any questions you might have.

Thanks,
Daniel

**Comment by bahamut657** [comment]
I'm interested to mantain the project. 
How to support this? 
Are there any milestones?

Regards 
Jacopo

**Comment by chdanielmueller** [comment]
Hey Jacopo

That's good to hear.
You can start looking at issues of other people.
And join us on the slack chat.

Cheers Daniel

**Comment by chdanielmueller** [comment]
@daniloab has taken over the project.
