### ISSUE TITLE
TypeError: Cannot read property 'cstNode' of undefined

### ISSUE THREAD

**Issue by timohe** [Surnet/swagger-jsdoc#274]
**Describe the bug**
I got a node application. When I first build it with `tsc` then run `node ./built/server.js`I get the following error:

````
/Users/timo/Documents/repos/tichu_backend/node_modules/swagger-jsdoc/src/specification.js:230
          const anchorString = anchor.cstNode.toString();
                                      ^
TypeError: Cannot read property 'cstNode' of undefined
    at /Users/timo/Documents/repos/tichu_backend/node_modules/swagger-jsdoc/src/specification.js:230:39
    at Array.forEach (<anonymous>)
    at build (/Users/timo/Documents/repos/tichu_backend/node_modules/swagger-jsdoc/src/specification.js:219:25)
    at Object.module.exports [as default] (/Users/timo/Documents/repos/tichu_backend/node_modules/swagger-jsdoc/src/lib.js:29:10)
    at Object.<anonymous> (/Users/timo/Documents/repos/tichu_backend/built/server.js:101:44)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
````

I also tried with version 6.0.1, same issue

**Expected behavior**
No error

**Additional context**
ts-node ver. 9.1.1, typescript ver. 4.2.4, "swagger-jsdoc": "6.0.0", "@types/swagger-jsdoc": "6.0.0", node v14.17.0

**Comment by daniloab** [comment]
can you paste an example of your yaml? and are you getting some error when running swagger-jsdoc?

can you provide a repo representing your implementation?

**Comment by timohe** [comment]
Hey. Thanks for the response. I was able to pinpoint the issue
````
        /**
	* @swagger
	* /users/register:
	*   post:
	*     summary: Register a new user
	*     tags:
	*        - user
	*     security: []
	*     requestBody:
	*       required: true
	*       content:
	*         application/json:
	*           schema:
	*             properties:
	*               name:
	*                 type: string
	*                 description: desc
	*                 example: abc
	**/
````

So on the last line I put **/ instead of */.
Will close this. If it would be somehow possible to give a more precise error message in those case, would be great.

**Comment by woxman** [comment]
> **Describe the bug** I got a node application. When I first build it with `tsc` then run `node ./built/server.js`I get the following error:
> 
> ```
> /Users/timo/Documents/repos/tichu_backend/node_modules/swagger-jsdoc/src/specification.js:230
>           const anchorString = anchor.cstNode.toString();
>                                       ^
> TypeError: Cannot read property 'cstNode' of undefined
>     at /Users/timo/Documents/repos/tichu_backend/node_modules/swagger-jsdoc/src/specification.js:230:39
>     at Array.forEach (<anonymous>)
>     at build (/Users/timo/Documents/repos/tichu_backend/node_modules/swagger-jsdoc/src/specification.js:219:25)
>     at Object.module.exports [as default] (/Users/timo/Documents/repos/tichu_backend/node_modules/swagger-jsdoc/src/lib.js:29:10)
>     at Object.<anonymous> (/Users/timo/Documents/repos/tichu_backend/built/server.js:101:44)
>     at Module._compile (internal/modules/cjs/loader.js:1068:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
>     at Module.load (internal/modules/cjs/loader.js:933:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:774:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
>     at internal/main/run_main_module.js:17:47
> ```
> 
> I also tried with version 6.0.1, same issue
> 
> **Expected behavior** No error
> 
> **Additional context** ts-node ver. 9.1.1, typescript ver. 4.2.4, "swagger-jsdoc": "6.0.0", "@types/swagger-jsdoc": "6.0.0", node v14.17.0

how fixed this problem......help me

**Comment by Sebastiao-Domingos** [comment]
C:\Users\domin\Documents\apis\escola\node_modules\swagger-jsdoc\src\specification.js:263
          const anchorString = anchor.cstNode.toString();
                                      ^

TypeError: Cannot read properties of undefined (reading 'cstNode')
    at C:\Users\domin\Documents\apis\escola\node_modules\swagger-jsdoc\src\specification.js:263:39        
    at Array.forEach (<anonymous>)
    at build (C:\Users\domin\Documents\apis\escola\node_modules\swagger-jsdoc\src\specification.js:253:25)
    at module.exports (C:\Users\domin\Documents\apis\escola\node_modules\swagger-jsdoc\src\lib.js:32:10)  
    at <anonymous> (c:\Users\domin\Documents\apis\escola\src\routes\index.ts:11:21)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.18.0

Iam getting this error.
How can I fixe this?

**Comment by 17Sergey** [comment]
Hi! I faced this issue and thought like what in the Earth is happening...I deleted all of my swagger markup and traced where was the error. For me it was just markup.

Have a nice day!
