### ISSUE TITLE
Question: how to use `failOnErrors` with CLI?

### ISSUE THREAD

**Issue by taschetto** [Surnet/swagger-jsdoc#278]
I'm using the following `npm` script to generate a JSON with my specs on CI:

```json
"openapi:generate": "yarn swagger-jsdoc -d src/swagger/swaggerDefinition.js src/routes/**/*.{js,yml,yaml} src/swagger/**/*.yml src/swagger/**/*.js -o swagger.json",
```

The problem is: I want this to fail on errors. Is there any way to use `failOnErrors` with the CLI version?

Thanks!

**Comment by daniloab** [comment]
What do you mean "I want this to fail on errors"?
