### ISSUE TITLE
Swagger ui blank screen (related issue?)

### ISSUE THREAD

**Issue by tamis-laan** [Surnet/swagger-jsdoc#288]
Could it be that this issue is related to swagger-jsdoc? 

https://github.com/scottie1984/swagger-ui-express/issues/273

**Comment by daniloab** [comment]
Hi @tamis-laan 

I believe don't have since the swagger-jsdoc do not have touch in UI and you are using a stable version. If you found anything related to us feel free to relate it.

**Comment by daniloab** [comment]
since the original issue it was closed we are closing this one.

**Comment by raul-macedo-freire** [comment]
Changing the middleware order has fixed this issue for me ( same for similar packages).
