### ISSUE TITLE
customfavIcon does not work

### ISSUE THREAD

**Issue by DinoscapeProgramming** [Surnet/swagger-jsdoc#309]
**Describe the bug**
I‘ve declared a variable (uiOpts) and have customCss, customSiteTitle and customfavIcon in it, the first both things are working, but not customfavIcon. The file I specified is published on my site (https://url.dinoscape.tk/favicon.webp).

**To Reproduce**

**Expected behavior**
I can‘t change the favicon of my site.

**Screenshots**
![DB846D68-23EA-4805-B72F-1030F0FF3DD8](https://user-images.githubusercontent.com/95239392/155140891-13734fc4-812d-4f8a-a005-382a5edd86f1.jpeg)
![D5741FA2-645D-47E9-92A1-C8EEBFB93799](https://user-images.githubusercontent.com/95239392/155142321-1973deee-a078-4af3-9eee-a3de928a14f3.jpeg)

**Tablet (yeah, i‘m using a tablet):**
 - OS: iOS
 - Browser: Safari
 - Version 14.6

**Additional context**
I tried to change the images in https://url.dinoscape.tk/docs/favicon-16x16.png and https://url.dinoscape.tk/docs/favicon-32x32.png, so the images changed, but it still doesn‘t work. Oh, and I’m using the version 3.0.

**Comment by DinoscapeProgramming** [comment]
I hope anyone can help me :)

**Comment by DinoscapeProgramming** [comment]
Oh, I saw your from switzerland, so we can speak German?

**Comment by DinoscapeProgramming** [comment]
Also ich bin Deutscher. Wenn man Englisch nicht so gut ist, dann entschuldige ich mich dafür.

**Comment by daniloab** [comment]
hi @DinoscapeProgramming the swagger-jsdoc does not handle UI configs. Probably you need to open an issue inside of swaggerUi to understand the better fix to your issue.

**Comment by DinoscapeProgramming** [comment]
> hi @DinoscapeProgramming the swagger-jsdoc does not handle UI configs. Probably you need to open an issue inside of swaggerUi to understand the better fix to your issue.

Oh, ups, my mistake 🤦‍♂️

**Comment by DinoscapeProgramming** [comment]
Sorry, I opened a wrong issue :(
