### ISSUE TITLE
integrate a docusarus to move the documentation to there

### ISSUE THREAD

**Issue by daniloab** [Surnet/swagger-jsdoc#318]
the main idea is to move the markdown documentation to a docusaurus page and make it easier to read these same docs, to add new ones, find it by adding a search bar and more improvements.

- [ ] add a docusaurus page
- [ ] move the docs to there
- [ ] has each docs by each existent docs from each version

**Comment by rockingrohit9639** [comment]
hey, @daniloab Can I work on this issue?

**Comment by daniloab** [comment]
> hey, @daniloab Can I work on this issue?

Sure @rockingrohit9639 feel free to work on it and I will help you with reviews

**Comment by rockingrohit9639** [comment]
> > hey, @daniloab Can I work on this issue?
> 
> Sure @rockingrohit9639 feel free to work on it and I will help you with reviews

Thank you for allowing me to work on this project. 
Can you please tell me where should I start, there is already a directory called `docs` in the root folder then what should I name docusaurus directory?

**Comment by daniloab** [comment]
> > > hey, @daniloab Can I work on this issue?
> > 
> > 
> > Sure @rockingrohit9639 feel free to work on it and I will help you with reviews
> 
> Thank you for allowing me to work on this project. Can you please tell me where should I start, there is already a directory called `docs` in the root folder then what should I name docusaurus directory?

Yes, in your pr I will just cleanup the docusaurus default content

**Comment by rockingrohit9639** [comment]
Hey @daniloab 
Please tell me if there is anything required in the documentation.
