### ISSUE TITLE
editor.swagger.io gives error

### ISSUE THREAD

**Issue by m0x31h0x64i** [Surnet/swagger-jsdoc#334]
**Describe the bug**

![image](https://user-images.githubusercontent.com/109550653/196495968-faacc81f-0c2d-4783-992b-7e1be3ac5869.png)

![image](https://user-images.githubusercontent.com/109550653/196496700-ad1db8ae-3c14-4615-9370-778b6a4c6913.png)

**To Reproduce**
1. Go to editor.swagger.io
2. paste the following code :
```
{
  openapi: '3.0.1',
  info: {
    title: 'APIs',
    version: '3.3.6',
    
    
    description: "<center>added 'x'</center>\n" +
      '            <center>added</center>'   
  },
}
```
3. See error

**Expected behavior**
no error.

**Desktop (please complete the following information):**
 - OS: Windows x64
 - Browser chrome Version 106.0.5249.119 (Official Build) (64-bit)

**Comment by daniloab** [comment]
looks like there is a problem with you yaml structure

try to open an issue in the official swagger repo
