### ISSUE TITLE
Update examples to comply to Swagger specification

### ISSUE THREAD

**Issue by kalinchernev** [Surnet/swagger-jsdoc#35]
Issue description:
- Relates to: #30
- [Detailed example](https://github.com/Surnet/swagger-jsdoc/pull/30#issuecomment-243800958) to change tags property

Tasks:
- update examples to comply to [swagger specification](http://swagger.io/specification/)
- include validations for the tags
- include tests to cover the validator functions

**Comment by drGrove** [comment]
Thanks for taking this @kalinchernev

**Comment by kalinchernev** [comment]
Hi @drGrove, it's a good opportunity for me to write some tests to raise the coverage.
So far, I have the feeling that it will take me a bit more time to figure out a smart way to add coverage for removing the logic of [string concatenation](https://github.com/Surnet/swagger-jsdoc/blob/master/lib/index.js#L104) for re-formatting the output.
Just updating the tags in the examples didn't meet some expectations I imposed, so I really feel the coverage is important..

**Comment by drGrove** [comment]
@kalinchernev, feel free to upload a PR whenever. Willing to try and help out where I can.

**Comment by kalinchernev** [comment]
Thanks @drGrove, so far I'm struggling a bit debugging the function, still learning debugging in node :)
And by the way, trying to understand the diff of the actual and expected schema, turns out the example expected schema fails at the http://bigstickcarpet.com/swagger-parser/www/index.html so it might be that the specification in the test comparison to be changed as well.
Will keep you posted!

**Comment by drGrove** [comment]
Awesome, thanks @kalinchernev!

It seems the first issue to solve is the tag[s] one. That should be a good start. I tried to fix [it][pastebin-fixed] in a pastebin, but [the validator][swagger-parser] doesn't seem to be able to pull from pastes.

It can from github tho, so with each fix that you attempt, if you push it to github you can just give them the raw url.

As far a JS debugging, i live in this land, so don't hesitate to ask and i'm always just a ping away:
dgrove on freenode
dgrove on irc.hashbang.sh

[swagger-parser]: http://bigstickcarpet.com/swagger-parser/www/index.html
[pastebin-fixed]: https://pastebin.com/raw/kq5ziidL

**Comment by kalinchernev** [comment]
Hi @drGrove a pull is now open, it includes the validated expectation file you provided.
Just wondering if there is a way to include a notice about this change in the update for users that have the previous tag and have to update to tags..
