### ISSUE TITLE
remove lodash.mergewith End of life lib and use alternative 

### ISSUE THREAD

**Issue by kamleshiitbhu** [Surnet/swagger-jsdoc#358]
**Describe the bug**
currently used lodash.mergewith module is marked as end of life and need to update with some alternative module

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by daniloab** [comment]
can you add a better description about your issue?
