### ISSUE TITLE
Vulnerability with dependency yaml@2.0.0-1

### ISSUE THREAD

**Issue by ankit201206** [Surnet/swagger-jsdoc#361]
There is a security vulnerability discovered with a deep-down dependency of yaml@2.0.0-1. It looks like this has been resolved with v2.2.2, so an upgrade of that dependency version to v2.2.2 seems to be in order.

**Comment by daniloab** [comment]
Hi, @ankit201206 thanks

can you send a pr fixing it, please?

**Comment by SuperBlahman** [comment]
There's a PR already from the dependency bot - https://github.com/Surnet/swagger-jsdoc/pull/360

**Comment by yaverin** [comment]
@daniloab , Hi! Please let us know, what is ETA of new version release with this fix?

**Comment by daniloab** [comment]
> @daniloab , Hi! Please let us know, what is ETA of new version release with this fix?

We need a fix in the yaml 2.2.2 dependabot pull request. Can someone fix this for us, please? Or check why the tests are breaking it

**Comment by guy-microsoft** [comment]
Vulnerability is still in there.
Is there going to be a fix soon?
