### ISSUE TITLE
Find alternative for concat-map as it is EOL

### ISSUE THREAD

**Issue by pratikkpatil** [Surnet/swagger-jsdoc#386]

**Comment by daniloab** [comment]
can you provide a context for issue?

**Comment by pratikkpatil** [comment]
concat-map which is being used in swagger-jsdoc is EOL(End of Life) module for which no latest versions are available. So, security vulnerability has been reported for usage of concat-map inside swagger-jsdoc. Need to find if we have any alternative to implement same logic as concat-map with any other node module.
