### ISSUE TITLE
Need way to turn off deprecation warnings

### ISSUE THREAD

**Issue by toefraz** [Surnet/swagger-jsdoc#44]
I am trying to document my API and am creating some schemas for body properties. One of the properties you can send in the body is named 'path', but when using swagger-jsdoc to generate the spec, I'm getting an error:

> You are using properties to be deprecated in v2.0.0
> Please update to align with the swagger v2.0 spec.
> [ 'path' ]

Looking through the code it looks like you are finding deprecated properties from the old spec and spitting out a warning if you see any property matching it even if it's a valid property. 

It would be nice to have a way to tell swagger-jsdoc that "hey I know what I'm doing, please turn off deprecation warnings".

And also it might be good to check if passed in properties are actual properties instead of denying it based solely on the property name.

I could submit a PR for this feature if you give me some direction on how you'd like to see it implemented.

Thanks!

**Comment by kalinchernev** [comment]
Hi @toefraz if you're really interested to help with this scenario, here's some information for start.
Initially, the module was (and still is) accepting specific property names in plural forms. In the last minor update, I introduced [this helper](https://github.com/Surnet/swagger-jsdoc/blob/master/lib/swagger-helpers.js#L75) which "decides" whether a given property name is to be deprecated. Honestly, I hadn't noticed this possible scenario.

Currently, the `tags` property is special, you can see an example how the community PRs suggested its handling [here](https://github.com/Surnet/swagger-jsdoc/blob/master/lib/swagger-helpers.js#L142). Thus, the path property could eventually be a similar scenario. Probably, it will be necessary to do that somewhere in the `RecursiveIterator` process, as paths is definitely not good on the level of tags, but ok in other cases. If paths is ok in any level, then making something similar as for the tags property might be just ok.

In the end, the functions that would hopefully be sufficient to refactor are `findDeprecated`, `seekWrong`, `_getSwaggerSchemaWrongProperties` and eventually `_organizeSwaggerProperties`.

Are you still interested into trying this out? :)

**Comment by toefraz** [comment]
@kalinchernev I think it's best to just ignore deprecation warnings for children of 'properties' objects. I just submitted a PR to do this. Do you agree with this approach?

**Comment by chdanielmueller** [comment]
Closed by merging of #45

**Comment by monk8800** [comment]
Hi guys, I seem some logic has been added, how do I go about actually removing the below warning

Please update to align with the swagger v2.0 spec.
[ 'definition' ]

**Comment by kalinchernev** [comment]
Hi @monk8800 just try to rename to ["definitions"](http://swagger.io/specification/#definitionsObject), hopefully it will be solved.

**Comment by monk8800** [comment]
@kalinchernev Thanks that did the trick
