### ISSUE TITLE
apis deep paths

### ISSUE THREAD

**Issue by chrishawn** [Surnet/swagger-jsdoc#58]
I had this working with a default express install
but now I moved my directory to match

`apis: [ './express/routes/*.js', '../lib/models/*.js' ]` 

I don't get any errors but no swagger objects are made except for my definition, which serves up fine.

Am I doing something wrong for this type of setup?

**Comment by kalinchernev** [comment]
Hi @chrishawn the input goes through the [glob](https://www.npmjs.com/package/glob) in the background. Can you check if the files are read by it with your expression?

**Comment by chrishawn** [comment]
![screen shot 2017-02-16 at 9 47 16 am](https://cloud.githubusercontent.com/assets/309639/23028448/f789a6ce-f42c-11e6-968b-013ec6012aaa.png)

nope, but that was helpful, i found it needed to be `apis: [ './express/routes/*.js', './lib/models/*.js' ]` relative to where node was started from not relative to the starting app.js file
