### ISSUE TITLE
Use JavaScript POJOs in definitions

### ISSUE THREAD

**Issue by c100k** [Surnet/swagger-jsdoc#62]
Good job on what you do on this project. I was wondering if it was possible to use POJOs in definitions instead of copying the properties.

Let's say I have a POJO

```javascript
function UserProfile(email, firstName, lastName) {
    this.email = email;
    this.firstName = firstName;
    this.lastName = lastName;
};
```

Currently in the definition I have to repeat the fields

```javascript
/**
 * @swagger
 * definitions:
 *   UserProfile:
 *     properties:
 *       email:
 *         type: string
 *       firstName:
 *         type: string
 *       lastName:
 *         type: string
 */
```

Do you think it is conceivable to use something like this :

```javascript
const UserProfile = require('../models/user-profile');

/**
 * @swagger
 * definitions:
 *   UserProfile:
 *     $ref: 'UserProfile'
 */
```

That would be awesome. I could work on a PR if it is possible.
Thanks.

**Comment by drGrove** [comment]
I think the issue with using POJOs is that it mostly goes against what this project is really made for, which is jsdoc based creation. Since this is Javascript and not Typescript we are not going to have the kind of typing necessary to make this be efficient either.

@chdanielmueller, @kalinchernev thoughts?

**Comment by kalinchernev** [comment]
I honestly don't feel capable of expressing an opinion on this, as it's my first time I hear POJO and I don't use Typescript at all.
My feeling is that what you speak about @c100k makes sense in terms of making a re-usable snippet of code to avoid repetition. However, swagger-jsdoc so far is just parsing documentation and generating swagger specification, it's not parsing any code at all, as one of the goals of having swagger specification on first place is to decouple your api definition from the api implementation. Code can be generated by codegen based on the specification. And my personal opinion is that the documentation should be just that - documentation.
I think that your idea is interesting and could be implemented by a separate project, where you select a given function or class (JavaScript you know :) which generates documentation based on code. I'd imagine that if there is a good parser of the POJO, then you'd be a temptation to jump directly to translating it to open api specification file format.

**Comment by c100k** [comment]
Indeed, you're right for the typing... It's not as simple as I thought... I had this idea :

```javascript
/**
  * @swagger
  * definitions:
  *   UserProfile
  *     type: object
  *     properties:
 */
function UserProfile(email, firstName, lastName) {
   /**
     * @swagger
     * email:
     *   type: string
     *   format: email
    */
    this.email = email;

   /**
     * @swagger
     * firstName:
     *   type: string
    */
    this.firstName = firstName;

   /**
     * @swagger
     * lastName:
     *   type: string
    */
    this.lastName = lastName;
};
```

And we would need to add in the options :

```javascript
const options = {
    swaggerDefinition: {
        info: {
            title: 'My Super API',
            version: '1.0.0',
            description: 'Documentation of my REST API',
        }
    },
    definitions: ['user-profile.js'],
    apis: ['route1.js', 'route-2.js'],
};
```

But maybe you're right about implementing this in a different project.

**Comment by kalinchernev** [comment]
@c100k maybe you can experiment a bit with a tool such as [AST](https://astexplorer.net/#/gist/f8044ec01eec7121e1e5fa003507d452/e879e3d2a8352783d56335dfb635d909d5a80f84) explorer as it breaks the code into JSON. Then, I think i'll be able to make some filtering on the data which makes sense, prepare it in a similar way as this module (which prepares data from comments) and then parse it with [swagger-parser](https://www.npmjs.com/package/swagger-parser).
Also, when I googled "swagger parser" this came on [1st result](https://github.com/swagger-api/swagger-parser). It seems it's realizing a similar idea.

**Comment by chdanielmueller** [comment]
@c100k: I do have the same opinion as @drGrove and @kalinchernev on this and think it is not something which should be implemented in this project. It would increase the maintenance effort more than it would bring value to the users of this package. But the idea itself might be worth the effort in a different project.

**Comment by dietergeerts** [comment]
Though JSDoc itself uses the asked functionality. So would it be that difficult to have it as a plugin for jsdoc, or use jsdoc to parse?
