### ISSUE TITLE
[Maintainer] GitHub settings

### ISSUE THREAD

**Issue by chdanielmueller** [Surnet/swagger-jsdoc#63]
Hi @kalinchernev and @drGrove 

I was thinking about changing some of the repository settings and would like to get your feedback on this.

Since this project is pretty popular with over 30'000 downloads a month on npm I think it would be useful to protect the master branch. I would recommend the following settings to make sure we do not merge any faulty and unreviewed code.
<img width="756" alt="branch protection" src="https://cloud.githubusercontent.com/assets/4051999/23918864/e8cb7e96-08f4-11e7-86d4-8525f774c707.png">

Furthermore it would be cool if we could decide on a merging style. I don't really have an opinion on the merging style but if there is the option to standardize the merges it might be useful.
<img width="745" alt="merging settings" src="https://cloud.githubusercontent.com/assets/4051999/23918850/dd3f2bb8-08f4-11e7-9a8f-f901bf0504ba.png">

I am keen to hear your opinions.

Thanks,
Daniel

**Comment by kalinchernev** [comment]
Hi @chdanielmueller,
It makes sense, of course. Actually, it's a pretty popular thing to have, so I'm for it. Although not a lot of development happens from several developers on a branch at the moment, I'd even suggest that only squash merging is allowed without rebase on master.

**Comment by drGrove** [comment]
Hi @chdanielmueller,

I think that forcing tests to run is an excellent idea.

re: squash merge, This tends to be very popular and I do think it's a good idea. The _only_ issue i see with this revolves around more than one user making changes to a PR (like @kalinchernev this isn't very likely), but this does affect [Contributions](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#common-reasons-that-contributions-are-not-counted). Only the opener of a PR and the person merging the commit will get the contribution.

**Comment by chdanielmueller** [comment]
I will set the settings as discussed. If there are problems with the merging style we can change that later again.

Thanks for your inputs.
