### ISSUE TITLE
[Maintainer] Signing Tags

### ISSUE THREAD

**Issue by drGrove** [Surnet/swagger-jsdoc#64]
Due to #63 being opened, this has lead me to think we should start GPG signing tags. This will ensure to our end users that we have verified what is in a tag ([Why Sign Tags](http://stackoverflow.com/a/12188977)). We can also set npm to handling this with the `npm version` command using [sign-git-tag](https://docs.npmjs.com/cli/version) config

**Comment by kalinchernev** [comment]
Hi,
I am open to adopt any new approach and requirement to make the releases safer. For this, I didn't know and I don't fully understand it, but again - I'm open to have better ways :)

**Comment by chdanielmueller** [comment]
Hi @drGrove,
I think increasing the security for the package's users would be a good thing. But I do not fully understand what we would need to change to implement GPG signing tags.
Can you explain what we would need to do?

**Comment by drGrove** [comment]
Hi @chdanielmueller,

To keep it simple, you'd need to 
1) generate a GPG key
2) Publish the key to a keyserver (pgp.mit.edu is where I keep my key)
3) Add your public key to Github
4) Commit as normal. If we use `npm version ${type}` and have signing enabled it will create a commit and then sign the tag associated to that commit
