### ISSUE TITLE
[Feature Request] To include recursive option for CLI

### ISSUE THREAD

**Issue by davistan** [Surnet/swagger-jsdoc#68]
Similar to the options.api, this will allow us to call it from CLI where we can expect the app to recurse into subdirectories.

Example:
`swagger-jsdoc -d swagger-doc.js -o api.json -r src/`

Thanks.

**Comment by kalinchernev** [comment]
Hi @davistan, can you try using a [blob pattern](https://github.com/Surnet/swagger-jsdoc/issues/58)?

**Comment by davistan** [comment]
Yes, I did try using ./src/*.js and it does not go deep, just the files in ./src/ only.

Also the apis options is not possible in .esdoc.json.

Nor, there are arguments in the CLI for setting options.

**Comment by kalinchernev** [comment]
Having the pattern **/*.js might work, I tried like this successfully:
```
swagger-jsdoc.js -d ./example/swaggerDef.js ./example/folder1/**/*.js ./example/folder2/**/*.js
```
![swagger jsdoc prs cloud9](https://cloud.githubusercontent.com/assets/1923476/25522618/e4b86954-2c03-11e7-9717-dbdb7d87f3da.png)

More on the module used in the background of figuring the [globs](https://github.com/isaacs/node-glob)

As far as I know, [comments are not feasible in JSON files](http://stackoverflow.com/questions/244777/can-comments-be-used-in-json). When you write the specification JSON files, you can directly go for a solution like [swagger-editor](http://editor.swagger.io/#!/) or have a split of JSON/YAML files making the spec via [this](https://github.com/Rebilly/generator-openapi-repo). This is a completely different approach though.

**Comment by davistan** [comment]
Yes, with ** it works in CLI as well. Thanks.
