### ISSUE TITLE
Code doesn't merge path objects from different files.

### ISSUE THREAD

**Issue by rnsell** [Surnet/swagger-jsdoc#78]
I'm working on a serverless api. The folder structure separates the api by path and then individual files to represent the operations and thus the http method. This means two comments regarding a path occur in two separate files, but they have different http methods (GET, PUT, etc). When I generate the JSON swagger doc the last file read has its properties in the same file.

In _organizeSwaggerProperties in swagger-helper.js the first conditional statement would trigger for path/paths, and it doesn't merge objects, thus the last read object would over write the previous state. Should this be patched to the below code where the objects are merged:

```
if (simpleProperties.indexOf(propertyName) !== -1) {

    var keyName = _correctSwaggerKey(propertyName);
    var definitionNames = Object
      .getOwnPropertyNames(pathObject[propertyName]);
    for (var k = 0; k < definitionNames.length; k = k + 1) {
      var definitionName = definitionNames[k];

      // Notice the merge function call here.
      swaggerObject[keyName][definitionName] =
        _objectMerge(swaggerObject[keyName][definitionName], pathObject[propertyName][definitionName]);
    }
  // Tags.
  }
```

**Comment by igor-savin-ht** [comment]
Can you please produce PR for this, preferably with unit test?

**Comment by willvincent** [comment]
Used @adam187's change, added a test.

PLEASE merge this PR, this is causing problems in another package that depends on swagger-jsdoc on my current project.  Without this fix, I'm stuck having to shove everything into a single external file, that's really unpleasant :)
