### ISSUE TITLE
Parameters should be an Array

### ISSUE THREAD

**Issue by rotexhawk** [Surnet/swagger-jsdoc#81]
I think there might be a bug when converting parameters. The type needs to be array but I got an object instead, which doesn't work with ReDoc.  Thank you. 

Sample From OpenAPI.
https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore-expanded.json#L135

**Comment by leehankyeol** [comment]
Parameters [are](https://github.com/Surnet/swagger-jsdoc/blob/master/docs/GETTING-STARTED.md#how-to-document-the-api) an array.

**Comment by drGrove** [comment]
@rotexhawk can you provide a sample of the output along with your input?

**Comment by kalinchernev** [comment]
Cannot reproduce.
