### ISSUE TITLE
Support for multiline comments without leading asterisk

### ISSUE THREAD

**Issue by Ohems** [Surnet/swagger-jsdoc#83]
## Request
Add support for documentation styles like
```
/**
  @swagger
  /ratings/{targetNamespace}:
    get:
      summary: List ratings in a given target namespace.
      description: |
          List ratings in a given target namespace.
          If requesting as a service user, unpublished ratings
          will not be returned.
   ...
**/
```
which currently break with various errors. swagger-jsdoc apparently expects every line to start with an asterisk symbol and therefore fails to parse multiline parameters properly.

## Reasoning
Leading asterisk characters can be very confusing for most editors. The editor fails to notice the indentation levels of the documentation due to the asterisk characters and managing the indentations becomes tedious. Also, some editors don't automatically add the asterisk when adding a new line which only adds to the manual work.

Not only that, but when writing comments like
```
/*
 * line1
 *   line2
 */
```
`line1` has 3 characters before it and `line2` has 5. This causes a bit of issues since standard indentations are usually 4 and 6 and the editor doesn't realise this, "missing" the right indentation level when pressing tab. The last space has to be added separately. It's possible to write like
```
/*
* line1
*   line2
*/
```
but this looks rather ugly IMO.

## Example
The following works:
```
  /**
   * @swagger
   * '/data':
   *    get:
   *      description: List data
   *      produces:
   *        - application/json
   *      responses:
   *        '200':
   *          description: Data
   */
```
And the following currently fails:
```
  /**
    @swagger
    '/data':
       get:
         description: List data
         produces:
           - application/json
         responses:
           '200':
             description: Data
   */
```
with an error:
```
<PATH_TO_PROJECT>/node_modules/js-yaml/lib/js-yaml/loader.js:171
  throw generateError(state, message);
  ^
YAMLException: duplicated mapping key at line 8, column 1:
    description: Data
    ^
    at generateError (<PATH_TO_PROJECT>/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (<PATH_TO_PROJECT>/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at storeMappingPair (<PATH_TO_PROJECT>/node_modules/js-yaml/lib/js-yaml/loader.js:308:7)
    at readBlockMapping (<PATH_TO_PROJECT>/node_modules/js-yaml/lib/js-yaml/loader.js:1071:9)
    at composeNode (<PATH_TO_PROJECT>/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readDocument (<PATH_TO_PROJECT>/node_modules/js-yaml/lib/js-yaml/loader.js:1492:3)
    at loadDocuments (<PATH_TO_PROJECT>/node_modules/js-yaml/lib/js-yaml/loader.js:1548:5)
    at load (<PATH_TO_PROJECT>/node_modules/js-yaml/lib/js-yaml/loader.js:1569:19)
    at Object.safeLoad (<PATH_TO_PROJECT>/node_modules/js-yaml/lib/js-yaml/loader.js:1591:10)
    at filterJsDocComments (<PATH_TO_PROJECT>/node_modules/swagger-jsdoc/lib/index.js:60:42)
    at module.exports (<PATH_TO_PROJECT>/node_modules/swagger-jsdoc/lib/index.js:106:32)
...
```

**Comment by drGrove** [comment]
Having a leading asterisk is part of the JSDoc styling. I don't think that moving away from a pretty rigid standard is a good idea.

**Comment by Ohems** [comment]
Then again, I believe it's rather easy to make the system so that it complies to the standard and supports my request, so it's an additional feature with no drawbacks. Just read all of the characters preceding `@swagger` on the same line and remove the same characters from each successive line when you convert it to YAML format.

**Comment by davidbonnet** [comment]
Leading asterisks for doc string comments were a terrible design decision.
Python coders must be laughing their heads off.

**Comment by crossan007** [comment]
Maybe a companion extension for VSCode to more intelligently support the editing of YAML-in-JSDoc?

That's a little beyond my skill level to build, but it would go a long way.
