### ISSUE TITLE
How to use this module with typescript?

### ISSUE THREAD

**Issue by zhaochy1990** [Surnet/swagger-jsdoc#84]
Hi, guys
I'm writing my node-express app with typescript, I installed 'swagger-jsdoc' and '@types/swagger-jsdoc'. but when I want to import swagger-jsdoc by `import * as swaggerJSDoc from 'swagger-jsdoc'`, an error occurs. `error| Module '"swagger-jsdoc"' resolves to a non-module entity and cannot be imported using this construct`. So, how to use this module with typescript?

**Comment by drGrove** [comment]
This is because we don't have a .d.ts in the repo. You'll want to install that from DefinitelyTyped using `npm i --save-dev @types/swagger-jsdoc`

**Comment by zhaochy1990** [comment]
yes, I install the @types definition, but the error stills there.

**Comment by gloorx** [comment]
Do `import swaggerJSDoc = require('swagger-jsdoc');`

**Comment by viveksagrawal** [comment]
does suggested import works for target = "es6" ?

**Comment by MashB** [comment]
> Hi, guys
> I'm writing my node-express app with typescript, I installed 'swagger-jsdoc' and '@types/swagger-jsdoc'. but when I want to import swagger-jsdoc by `import * as swaggerJSDoc from 'swagger-jsdoc'`, an error occurs. `error| Module '"swagger-jsdoc"' resolves to a non-module entity and cannot be imported using this construct`. So, how to use this module with typescript?

How did you configure path to API docs ? does it support TS files as path ?

**Comment by emirhg** [comment]
> > Hi, guys
> > I'm writing my node-express app with typescript, I installed 'swagger-jsdoc' and '@types/swagger-jsdoc'. but when I want to import swagger-jsdoc by `import * as swaggerJSDoc from 'swagger-jsdoc'`, an error occurs. `error| Module '"swagger-jsdoc"' resolves to a non-module entity and cannot be imported using this construct`. So, how to use this module with typescript?
> 
> How did you configure path to API docs ? does it support TS files as path ?

The CLI works straight forward
swagger-jsdoc -d swaggerDef.json src/routes/**/**.ts

**Comment by ypicard** [comment]
I'm not sure I understand how to use this package with typescript:
I tried:
```
import swaggerJSDoc from 'swagger-jsdoc';
```
and
```
const swaggerJSDoc = require('swagger-jsdoc');
```
but I get this error:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: my-project/node-api/node_modules/swagger-jsdoc/index.js
require() of ES modules is not supported.
require() of my-project/node-api/node_modules/swagger-jsdoc/index.js from my-project/node-api/src/app.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from my-project/node-api/node_modules/swagger-jsdoc/package.json.
```

**Comment by eliasffyksen** [comment]
@ypicard I get the same problem, it seams to be a problem in the newest version.
If you do `npm install swagger-jsdoc@6.1.0` it works fine for me. I'm guessing that this happens because it was updated to a ES6 module and the typescript compilation attempts to import it with `require`.

**Comment by serbanmunteanu** [comment]
> @ypicard I get the same problem, it seams to be a problem in the newest version.
> If you do `npm install swagger-jsdoc@6.1.0` it works fine for me. I'm guessing that this happens because it was updated to a ES6 module and the typescript compilation attempts to import it with `require`.

You save me 🥇
