### ISSUE TITLE
"Lite" version of swagger-jsdoc - exlude `cli` version

### ISSUE THREAD

**Issue by cikasfm** [Surnet/swagger-jsdoc#92]
Hi!

My builds are becoming quite heavy when using `swagger-jsdoc` primarily due to the reason that it using `chokidar` which depends on `fsevents` which depends on `node-gyp`.

`node-gyp` needs to be re-compiled on Unix / OS X from time to time when I do my installs and this takes forever.
Looking deeper into the code - that functionality used only by the `CLI` version of `swagger-jsdoc`, so I though - maybe we could split this project into 2 - one purely for generating the docs, and another - purely for `CLI` purposes, which could depend on the first one as "binary" dependency.

What do you think?

**Comment by kalinchernev** [comment]
`chokidar` has been removed.
