### ISSUE TITLE
Update documentation for usage

### ISSUE THREAD

**Issue by bpkennedy** [Surnet/swagger-jsdoc#93]
When specifying the path to the api routes, it currently requires relative to where node is started from and NOT from the app.js.  Please clarify this in documentation.  I've read several articles that all claim it is relative to the app.js which is incorrect.  I spent about 4 hours tinkering around before I happened upon a helpful closed Issue where someone found the same
```
var options = {
  swaggerDefinition: {
    info: {
      title: 'Hello World',
      version: '1.0.0',
    },
  },
  apis: ['./api/routes/*.js'], // Path to the API docs RELATIVE TO NODE START AND NOT APP.JS
};
```

**Comment by DylanC** [comment]
@bpkennedy - I agree. This badly needs to be updated. I wasted hours thinking the path is relative to app.js and finally to find out its not.

**Comment by kalinchernev** [comment]
Notes have been added in examples and in documentation.
