### ISSUE TITLE
Output to YAML format

### ISSUE THREAD

**Issue by Harikrishnan-Selvaraj** [Surnet/swagger-jsdoc#94]
is there any config that will enable to generate yaml output instead of JSON?

**Comment by kalinchernev** [comment]
Apart from the suggestion on dumping the specification through Node API, the CLI also supports this feature https://github.com/Surnet/swagger-jsdoc/blob/master/docs/CLI.md#specify-output-file-optional i.e. just add the extension in the desired file name on the `--output` option.
