### ISSUE TITLE
Support 3.0 syntax with components

### ISSUE THREAD

**Issue by MartinMuzatko** [Surnet/swagger-jsdoc#95]
Swagger-jsdoc should be able to generate definitions using the swagger 3.0 syntax.
E.g.: https://swagger.io/docs/specification/data-models/data-types/
Instead of putting `components` into paths, it should be used like `definitions`

**Comment by misanche** [comment]
Yes it would be nice if it supports also OpenAPI 3.0

**Comment by lehno** [comment]
Will it be possible?

**Comment by wiesson** [comment]
I'm also looking for version 3 :)

**Comment by eljefedelrodeodeljefe** [comment]
Might be a duplicate of #65

**Comment by MartinMuzatko** [comment]
Agreed! closing this issue. When first searching for this, I didn't know that v3 is the new "OPEN API".
Thanks!
