### ISSUE TITLE
Include filepath of offender on warning/errors

### ISSUE THREAD

**Issue by rkmax** [Surnet/swagger-jsdoc#99]
In my case I have the jsdoc aside the code, so i have spread a lot of jsdoc comments everywhere, it would be nice if the file path is include withtin the message

```
You are using properties to be deprecated in v2.0.0
Please update to align with the swagger v2.0 spec.
[ 'response' ]
```

**Comment by kalinchernev** [comment]
Deprecation messages have been removed.
